### ISSUE TITLE
Android N crash

### ISSUE THREAD

**Issue by yuriymyronovych** [RuedigerMoeller/fast-serialization#124]
I am using version 2.43 which cause the following crash on new Android N

java.lang.NoSuchMethodException: newInstance [class java.lang.Class, long]
                                                                     at org.objenesis.instantiator.android.Android18Instantiator.getNewInstanceMethod(Android18Instantiator.java:62)
                                                                     at org.objenesis.instantiator.android.Android18Instantiator.<init>(Android18Instantiator.java:38)
                                                                     at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:86)
                                                                     at org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:91)
                                                                     at org.nustaq.serialization.FSTObjenesisInstantiator.<init>(FSTObjenesisInstantiator.java:38)
                                                                     at org.nustaq.serialization.FSTConfiguration$4.getInstantiator(FSTConfiguration.java:359)
                                                                     at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:129)
                                                                     at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:130)
                                                                     at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:97)
                                                                     at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:84)
                                                                     at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:80)
                                                                     at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:756)
                                                                     at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:432)
                                                                     at org.nustaq.serialization.FSTConfiguration.createAndroidDefaultConfiguration(FSTConfiguration.java:362)
                                                                     at org.nustaq.serialization.FSTConfiguration.createAndroidDefaultConfiguration(FSTConfiguration.java:351)

**Comment by RuedigerMoeller** [comment]
see #121
