### ISSUE TITLE
Serializing a collection that is concurrently modified (reproducible)

### ISSUE THREAD

**Issue by artur-tamazian** [RuedigerMoeller/fast-serialization#138]
FST is performing great most of the time, but we keep getting exceptions like the one below from time to time. I was trying to reproduce it, but with no luck for some time already (UPD: see test case in comment below). @RuedigerMoeller maybe you can suggest what to look at?

The code I use:

```
public class FstSerializer implements Serializer {

	private static final FSTConfiguration FST = createConfiguration();

	private static FSTConfiguration createConfiguration() {
		FSTConfiguration configuration = FSTConfiguration.createDefaultConfiguration();

		configuration.setShareReferences(true);

		configuration.registerClass(Request.class);
		configuration.registerClass(Response.class);
		// .... (about 10 more)

		return configuration;
	}

	@Override
	public byte[] serialize(Serializable object) {
		return FST.asByteArray(object);
	}

	@Override
	public Object deserialize(byte[] bytes) {
		return FST.asObject(bytes);
	}
 }
```

Sample exception:

```
java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:8 loader:WebappClassLoader
  context: /app
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@2f2bf0e2

	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1124) ~[fst-2.47.jar:na]
	at com.callfire.amqp.transport.util.serialization.FstSerializer.deserialize(FstSerializer.java:66) ~[callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at com.callfire.amqp.transport.util.serialization.MessagesSerializer.deserialize(MessagesSerializer.java:53) ~[callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at com.callfire.amqp.transport.inbound.RequestsConsumer.consume(RequestsConsumer.java:57) [callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at com.callfire.amqp.transport.inbound.RequestsConsumer.run(RequestsConsumer.java:45) [callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.RuntimeException: class not found CLASSNAME:8 loader:WebappClassLoader
  context: /app
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.apache.catalina.loader.StandardClassLoader@2f2bf0e2

	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:472) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:933) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:343) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.serializers.FSTCollectionSerializer.instantiate(FSTCollectionSerializer.java:92) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:497) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:366) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.serializers.FSTMapSerializer.instantiate(FSTMapSerializer.java:78) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:497) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:366) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readArrayNoHeader(FSTObjectInput.java:905) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readArray(FSTObjectInput.java:885) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateArray(FSTObjectInput.java:456) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:425) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:360) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241) ~[fst-2.47.jar:na]
	... 6 common frames omitted
Caused by: java.lang.ClassNotFoundException: 8
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720) ~[catalina.jar:7.0.53]
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571) ~[catalina.jar:7.0.53]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45]
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:197) ~[fst-2.47.jar:na]
	... 42 common frames omitted
```

It's not always CLASSNAME:8, sometimes it was "[J" (which corresponds to long[]), empty or something else. I would be happy to provide a unit test, but whatever I try the code always passes and only fails on production (not always) (UPD: see test case below).

Sometimes it's like this:

```
java.io.IOException: java.lang.RuntimeException: unable to find class for code 253
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1124) ~[fst-2.47.jar:na]
	at com.callfire.amqp.transport.util.serialization.FstSerializer.deserialize(FstSerializer.java:66) ~[callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at com.callfire.amqp.transport.util.serialization.MessagesSerializer.deserialize(MessagesSerializer.java:53) ~[callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at com.callfire.amqp.transport.inbound.RequestsConsumer.consume(RequestsConsumer.java:57) [callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at com.callfire.amqp.transport.inbound.RequestsConsumer.run(RequestsConsumer.java:45) [callfire-rpc-3.0.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.RuntimeException: unable to find class for code 253
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:180) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:472) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:933) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:343) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.serializers.FSTCollectionSerializer.instantiate(FSTCollectionSerializer.java:92) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:497) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:366) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.serializers.FSTMapSerializer.instantiate(FSTMapSerializer.java:78) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:497) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:366) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readArrayNoHeader(FSTObjectInput.java:905) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readArray(FSTObjectInput.java:885) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateArray(FSTObjectInput.java:456) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:425) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:360) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307) ~[fst-2.47.jar:na]
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241) ~[fst-2.47.jar:na]
	... 6 common frames omitted
```

I also tried to register classes like this, but it didn't change anything:

```
FSTClazzNameRegistry registry = configuration.getClassRegistry();
registry.registerClass(Request.class, 201, configuration);

```

byte[] arrays are received as a RabbitMQ message payload and are not empty or suspiciously small.
The code above is deployed on several hosts and is the same everywhere. We have an ability to switch serialization implementation at runtime and standard java implementation works well, so it doesn't look like some transport/corrupt array issue.

Please let me know if you see anything wrong with the library usage or if you can suggest any additional  testcase.

FST version: 2.47

**Comment by artur-tamazian** [comment]
Here's the test that fails when serializing a collection which is being modified at the same time. I start several threads that add timestamps to the queue (you might want to increase the number to make sure test fails). After all of them start doing their jobs, I start to do serialization/deserialization using default FST configuration.


```
import java.io.Serializable;
import java.util.ArrayDeque;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.LongAdder;

import org.junit.Test;
import org.nustaq.serialization.FSTConfiguration;

public class Issue138Test {

	public static class TestClass implements Serializable {
		public ArrayDeque<Long> arrayDeque = new ArrayDeque<>();
		public LongAdder longAdder = new LongAdder(); // everything works if you comment this line
	}

	@Test
	public void testMutableObjectSerialization() throws InterruptedException {
		FSTConfiguration configuration = FSTConfiguration.createDefaultConfiguration();

		TestClass testObject = new TestClass();

		int threadsNumber = 20;
		int iterationsCount = 10000;

		CountDownLatch allThreadsWorkingLatch = new CountDownLatch(threadsNumber);
		CountDownLatch allThreadsDoneLatch = new CountDownLatch(threadsNumber);

		for (int i = 0; i < threadsNumber; i++) {
			new Thread() {
				@Override
				public void run() {
					allThreadsWorkingLatch.countDown();
					for (int j = 0; j < iterationsCount; j++) {
						testObject.arrayDeque.add(System.currentTimeMillis());
						try {
							Thread.sleep(1);
						}
						catch (InterruptedException e) {}
					}
					allThreadsDoneLatch.countDown();
				}
			}.start();
		}

		// wait untill all threads start modifying the collection and start serializing after that
		allThreadsWorkingLatch.await();

		while (allThreadsDoneLatch.getCount() > 0) {
			byte[] bytes = configuration.asByteArray(testObject);
			configuration.asObject(bytes);
		}
	}
}
```

Test always fails flor me with 

> java.io.IOException: java.lang.RuntimeException: unknown object tag -19

**Comment by RuedigerMoeller** [comment]
Hi, sorry for late answer. 
I am definitely not willing to support serialization with concurrent modification of the object graph, as this is a performance nightmare.
I don't even buy that Default serialization handles this correctly, because basically this would require synchronization all over the place, and I don't see code anywhere in the default impl dealing with that.

My advice: handle synchronization from outside, e.g. synchronize serialization and modification using a lock in your application.
