### ISSUE TITLE
Serializing and Deserializing two versions of the same class

### ISSUE THREAD

**Issue by diogoeag** [RuedigerMoeller/fast-serialization#158]
Hi, 

We areusing FST 1.x and we have a situation where during application upgrades, some classes change (in a controlled way such as only adding or removing fields, never change types) and I would like to know if there is any support on FST to annotate or be resilient to these types of situations.

eg.: 

Serialize the class in a system where class is in this version:
class Person { String name; }

Deserialize the class in a upgraded instance that communicates over the network with the same class in this version:
class Person { String name; String address; }

We are observing the following exception while deserializing:
`Caused by: java.lang.ArrayIndexOutOfBoundsException: 49
	at de.ruedigermoeller.serialization.FSTObjectInput.readFByte(FSTObjectInput.java:1042) ~[fst-1.63.jar:na]
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:242) ~[fst-1.63.jar:na]
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:544) ~[fst-1.63.jar:na]
	at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:406) ~[fst-1.63.jar:na]
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262) ~[fst-1.63.jar:na]
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230) ~[fst-1.63.jar:na]
	at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:210) ~[fst-1.63.jar:na]`

Any way to get around this in these particular situations?

**Comment by RuedigerMoeller** [comment]
versioning is not supported in FST. Reason is the massive overhead required in order to serialize version-safe. One workaround is to not modify the initial class but create a subclass PersonV2.
