### ISSUE TITLE
unknown object tag -84

### ISSUE THREAD

**Issue by ItsHarry** [RuedigerMoeller/fast-serialization#166]
```java
[23:57:34] [Server thread/WARN]: java.io.IOException: java.lang.RuntimeException: unknown object tag -84
[23:57:34] [Server thread/WARN]: 	at com.itsharry.libraries.fst.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
[23:57:34] [Server thread/WARN]: 	at com.itsharry.SLAPI.load(SLAPI.java:27)
[23:57:34] [Server thread/WARN]: 	at com.itsharry.IW.loadDatFiles(IslandWorld.java:701)
[23:57:34] [Server thread/WARN]: 	at com.itsharry.IW.onEnable(IslandWorld.java:249)
[23:57:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[23:57:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[23:57:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[23:57:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[23:57:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[23:57:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[23:57:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[23:57:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[23:57:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[23:57:34] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[23:57:34] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:57:34] [Server thread/WARN]: Caused by: java.lang.RuntimeException: unknown object tag -84
[23:57:34] [Server thread/WARN]: 	at pl.islandworld.libraries.fst.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:430)
[23:57:34] [Server thread/WARN]: 	at pl.islandworld.libraries.fst.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:360)
[23:57:34] [Server thread/WARN]: 	at pl.islandworld.libraries.fst.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327)
[23:57:34] [Server thread/WARN]: 	at pl.islandworld.libraries.fst.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307)
[23:57:34] [Server thread/WARN]: 	at pl.islandworld.libraries.fst.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
[23:57:34] [Server thread/WARN]: 	... 14 more
```

I'm trying to read a file that was created using Java's ObjectOutputStream. I simply replaced "ObjectInputStream" with "FSTObjectInput", but it throws the error above.

JDK: 1.8.0_65
OS: Windows 7

**Comment by RuedigerMoeller** [comment]
fst is not binary compatible, but "source-compatible". You cannot read files created with jdk serialization

**Comment by ItsHarry** [comment]
Ah I see, I will convert the files then from JDK serialization -> FST serialization. Thanks
