### ISSUE TITLE
ArrayIndexOutOfBoundsException by using writeObject() calls many times (> Integer.MAX_VALUE+1)

### ISSUE THREAD

**Issue by MrCodeGenEric** [RuedigerMoeller/fast-serialization#179]
If we call the method writeObject() of FSTObjectOutput many times ( > Integer.MAX_VALUE+1), then we get the follow exception

Caused by: java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at org.nustaq.serialization.FSTObjectOutput.getCachedFI(FSTObjectOutput.java:294)
        at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:317)
        at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:284)
        at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:193)

The Methode writeObject() increment "curDepth" without decrement "curDepth". It seems to be a bug.

**Comment by RuedigerMoeller** [comment]
seems you ar right ..

**Comment by RuedigerMoeller** [comment]
fixed with 2.49

**Comment by fireflyhoo** [comment]
天啦噜个fuck!!!
