### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by dubboy** [RuedigerMoeller/fast-serialization#184]
java.io.IOException: java.lang.NullPointerException
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243) ~[fst-2.45.jar:?]
        at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1122) ~[fst-2.45.jar:?]
java.io.IOException: java.lang.NullPointerException
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243) ~[fst-2.45.jar:?]
        at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1122) ~[fst-2.45.jar:?]

Fst Version:fst-2.45.jar

FstUtil:
public class FstUtils {

    public FstUtils() {
    }

    private static FSTConfiguration configuration = FSTConfiguration.createMinBinConfiguration();

    public static byte[] serializeByte(Object t) {
        return configuration.asByteArray(t);
    }

    public  static  Object deserializeByte(byte[] bytes) {
        return configuration.asObject(bytes);
    }
}

服务器重启有几率触发这个问题(Server restart has a chance to trigger this problem)

**Comment by RuedigerMoeller** [comment]
maybe a multithreading related issue during initial build up of metadata (FSTClassInfo).

* try 2.50, I made some fixes in this area (actually an undisclosed company made a reproducable testcase of 2000+ generated classes to reproduce this), has been fixed
* if this does not help please try to create a testcase reproducing this

**Comment by RuedigerMoeller** [comment]
seems fixed with 2.5x as no further response
