### ISSUE TITLE
While Conneting to Neo4j From Android I'm getting this error.

### ISSUE THREAD

**Issue by Prateek218** [RuedigerMoeller/fast-serialization#201]
Need help!!!
```
06-22 16:12:48.797 4281-4281/com.example.prateek.neo4jtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.prateek.neo4jtest, PID: 4281
                                                                             java.lang.NoClassDefFoundError: java.net.StandardSocketOptions
                                                                                 at org.neo4j.driver.internal.net.ChannelFactory.create(ChannelFactory.java:39)
                                                                                 at org.neo4j.driver.internal.net.SocketClient.start(SocketClient.java:124)
                                                                                 at org.neo4j.driver.internal.net.SocketConnection.startSocketClient(SocketConnection.java:92)
                                                                                 at org.neo4j.driver.internal.net.SocketConnection.<init>(SocketConnection.java:67)
                                                                                 at org.neo4j.driver.internal.net.SocketConnector.createConnection(SocketConnector.java:77)
                                                                                 at org.neo4j.driver.internal.net.SocketConnector.connect(SocketConnector.java:50)
                                                                                 at org.neo4j.driver.internal.net.pooling.SocketConnectionPool$ConnectionSupplier.get(SocketConnectionPool.java:204)
                                                                                 at org.neo4j.driver.internal.net.pooling.SocketConnectionPool$ConnectionSupplier.get(SocketConnectionPool.java:186)
                                                                                 at org.neo4j.driver.internal.net.pooling.BlockingPooledConnectionQueue.acquire(BlockingPooledConnectionQueue.java:96)
                                                                                 at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquireConnection(SocketConnectionPool.java:137)
                                                                                 at org.neo4j.driver.internal.net.pooling.SocketConnectionPool.acquire(SocketConnectionPool.java:76)
                                                                                 at org.neo4j.driver.internal.DirectConnectionProvider.acquireConnection(DirectConnectionProvider.java:45)
                                                                                 at org.neo4j.driver.internal.NetworkSession.acquireConnection(NetworkSession.java:340)
                                                                                 at org.neo4j.driver.internal.NetworkSession.run(NetworkSession.java:104)
                                                                                 at org.neo4j.driver.internal.NetworkSession.run(NetworkSession.java:94)
                                                                                 at com.example.prateek.neo4jtest.MainActivity$1.onClick(MainActivity.java:29)
                                                                                 at android.view.View.performClick(View.java:4438)
                                                                                 at android.view.View$PerformClick.run(View.java:18431)
                                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:149)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
```

**Comment by RuedigerMoeller** [comment]
nice. that's not an fst issue
