### ISSUE TITLE
Not support netty ByteBufInputStream/ByteBufOutputStream

### ISSUE THREAD

**Issue by hank-whu** [RuedigerMoeller/fast-serialization#221]
public class FstSerializer implements Serializer {
	private static final FSTConfiguration fst = FSTConfiguration.createDefaultConfiguration();

	private static FstSerializer serializer = new FstSerializer();

	public static FstSerializer getInstance() {
		return serializer;
	}

	@Override
	public void serialize(ByteBufOutputStream outputStream, Object obj) throws IOException {
		FSTObjectOutput fstObjectOutput = fst.getObjectOutput(outputStream);
		fstObjectOutput.writeObject(obj);
		fstObjectOutput.flush();
		outputStream.flush();
	}

	@Override
	@SuppressWarnings("unchecked")
	public <T> T deserialize(ByteBufInputStream #inputStream, Class<T> clazz) throws IOException {
		try {
			return (T) fst.getObjectInput(inputStream).readObject();
		} catch (ClassNotFoundException e) {
			throw new IOException(e);
		}
	}
}

**Comment by hank-whu** [comment]
16:37:39.728 [nioEventLoopGroup-2-2] ERROR benchmark.rpc.netty.server.handler.BenchmarkServerHandler - Exception caught on [id: 0xee8b7f2f, L:/127.0.0.1:8080 ! R:/127.0.0.1:56803], 
io.netty.handler.codec.DecoderException: java.io.IOException: java.io.IOException: Failed to read the next byte
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.io.IOException: Failed to read the next byte
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at benchmark.rpc.serializer.FstSerializer.deserialize(FstSerializer.java:31)
	at benchmark.rpc.netty.server.codec.ProtocolDecoder.decode(ProtocolDecoder.java:32)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 17 common frames omitted
Caused by: java.io.IOException: Failed to read the next byte
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:294)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFShort(FSTStreamDecoder.java:366)
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:163)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478)
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:938)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
	... 22 common frames omitted

**Comment by hank-whu** [comment]
my fault, it's ok.
please close this issue.
