### ISSUE TITLE
JDK compatibility jdk1.8.0_112 vs jdk1.8.0_121

### ISSUE THREAD

**Issue by tmccore** [RuedigerMoeller/fast-serialization#224]
Hi,

We are running into issues between Java versions using FST version: 2.54. jdk1.8.0_112 works fine, however using jdk1.8.0_121, we are noticing the following exceptions:
        
at org.jboss.remoting.marshal.serializable.SerializableUnMarshaller.read(SerializableUnMarshaller.java:123)
        at org.jboss.remoting.transport.socket.ServerThread.versionedRead(ServerThread.java:907)
        at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:761)
        at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:751)
        at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:548)
        at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
        at org.jboss.aop.joinpoint.MethodInvocation.readExternal(MethodInvocation.java:382)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:548)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:712)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor751.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:609)
        at org.nustaq.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:574)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:559)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
        ... 16 more
Caused by: java.io.IOException: java.lang.RuntimeException: unknown object tag -65
        at org.nustaq.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:1076)
        at org.nustaq.serialization.FSTObjectInput$MyObjectStream.defaultReadObject(FSTObjectInput.java:1362)
        at java.rmi.MarshalledObject.readObject(MarshalledObject.java:153)
        ... 26 more
Caused by: java.lang.RuntimeException: unknown object tag -65
        at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:434)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:364)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:712)
        at org.nustaq.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:1066)
        ... 28 more

Is this related to (JDK-8155760) http://www.oracle.com/technetwork/java/javase/8u121-relnotes-3315208.html ? Is there a workaround for this.

Thanks in advance.

**Comment by tmccore** [comment]
Hi, Do you have any update on this ?

**Comment by RuedigerMoeller** [comment]
nope, haven't found time to look into this, sorry

**Comment by RuedigerMoeller** [comment]
Does this occur when using mixed versions of JDK or does it occur even when sender and receiver run _121 ?

Can you figure out which class exactly causes the trouble (e.g. by reducing the transmitted/read object to the minimum viable error testcase ?)

**Comment by martinrosstmc** [comment]
It happens when both run the same version.  Didn't try cross version.  The issue we have reproducing it is that it because of Proxy classes and jboss class loading it isn't easily possible to isolate. I will try to do so.

**Comment by martinrosstmc** [comment]
I have confirmed that I can deserialize the object graph after serializing it in same VM.  I don't see any exceptions.

The failure happens in the MarshalledObject.java readObject method....  Not sure if this is related to the serialization changes in 121 or something else.

java.rmi.MarshalledObject.readObject(ObjectInputStream) MarshalledObject.java:153

**Comment by martinrosstmc** [comment]
I think this was the commit for the security tightening https://github.com/dmlloyd/openjdk/commit/c1e6fc9445fa31b6058a758907e9bc8aa088a17d

**Comment by martinrosstmc** [comment]
Serializing
MarshalledObject<String> mo = new MarshalledObject<String>("test");
byte barray2[] = conf.asByteArray(mo);
oos.writeInt(barray2.length);
oos.write(barray2);

and deserializing
		 int len2 = ((ObjectInputStream)inputStream).readInt();
		 byte buffer2[] = new byte[len2];
		 while (len2 >0)
			 len2 -= inputStream.read(buffer2, buffer2.length - len2, len2);
		 FSTObjectInput in2 = conf.getObjectInput(buffer2);
		 try {
			 in2.readObject();
		 } catch (Throwable t) {
			 logger.error("Error deserializing " + inputStream + " with " + ReflectionToStringBuilder.toString(conf.getClassRegistry()) + " using " + conf.getClassLoader(),t);
			 throw t;
		 }
		 finally {
			 //preventLargeDanglingBuffers(in);
		 }

generates 
java.io.IOException: java.lang.reflect.InvocationTargetException
aused by: java.lang.RuntimeException: unknown object tag -87
        at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:434)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:364)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:712)

**Comment by martinrosstmc** [comment]
On a separate VM via RMI

**Comment by martinrosstmc** [comment]
One other comment.  Regular java serialization works on the object.

**Comment by martinrosstmc** [comment]
So what is weird is that java.rmi.MarshalledObject for FSTClazzInfo has requiresCompatibilityMode = false .  
It looks like FSUtil.findPrivateMethod is throwing
java.lang.NoSuchMethodException: java.rmi.MarshalledObject.readObject(java.io.ObjectInputStream)

I think the issue is caused by addition of readObject and running different JVM versions (I reported the same incorrectly before).  One side is running in compatible mode and other is not.  

Is there a way to force compatibility mode? Or if we need to write a custom serializer how can we force to use compatible mode?

**Comment by RuedigerMoeller** [comment]
compatible mode == emulate JDK default serialization.

Once you define a custom serializer it will override everything.
