### ISSUE TITLE
When the FSTObjectInput.readObject fails, any chance of more info?

### ISSUE THREAD

**Issue by RuedigerMoeller** [RuedigerMoeller/fast-serialization#225]
[transferred from kontraktor #58]
I think this is the culprit, names have been changed to protect the innocent.

```json
{  
"styp":"array",
"seq":[  
  2,
  {  
     "typ":"call",
     "obj":{  
        "isContinue":0,
        "queue":0,
        "futureKey":1,
        "receiverKey":1,
        "cb":null,
        "args":null,
        "method":"getProducts",
        "serializedArgs":"{\"styp\":\"array\",\"seq\":[1,{\"typ\":\"uk.co.example.Application\",\"obj\":{\"numberOfDogs\":12,\"extraInformation\":{\"typ\":\"list\",\"obj\":[0]},\"advance\":{\"typ\":\"java.math.BigDecimal\",\"obj\":[\"1000\"]},\"grossHousehold\":null,\"startDate\":null,\"questions\":{\"typ\":\"uk.co.example.Questions\",\"obj\":{\"numberOfThings\":null,\"numberOfMissed\":null,\"numberOfMissedOther\":null,\"everHadBeef\":null,\"everMadeHouse\":null,\"missedPaymentsOnThingy\":null}},\"applicants\":{\"typ\":\"list\",\"obj\":[0]},\"propertyDetails\":null,\"authorises\":\"Y\",\"applicationName\":null,\"reference\":null,\"campaign\":null,\"ddBankAccount\":null,\"employmentStatus\":null,\"filterResults\":\"N\",\"homeOwner\":null,\"purpose\":null,\"sourcing\":null,\"stage\":null,\"userId\":\"stdclient\"}}]}"
     }
  },
  2
]
}
```

**Comment by davidwynter** [comment]
The original question went missing in the transfer to this repo. Here it is

Version 4.18 of Kontraktor. When I get a failure with the de/serialization, probably due to my code, it is very hard to find the cause.
E.g. here is a typical trace:

`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.nustaq.serialization.serializers.FSTCPThrowableSerializer.instantiate(FSTCPThrowableSerializer.java:42)
at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:501)
at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
at org.nustaq.serialization.FSTObjectInput.readArrayNoHeader(FSTObjectInput.java:910)
at org.nustaq.serialization.FSTObjectInput.readArray(FSTObjectInput.java:890)
at org.nustaq.serialization.FSTObjectInput.instantiateArray(FSTObjectInput.java:460)
at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:429)
at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:364)
at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:302)
at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1137)
at org.nustaq.kontraktor.remoting.encoding.RemoteCallEntry.unpackArgs(RemoteCallEntry.java:140)
at org.nustaq.kontraktor.remoting.base.ConnectionRegistry.processRemoteCallEntry(ConnectionRegistry.java:430)
at org.nustaq.kontraktor.remoting.base.ConnectionRegistry.receiveObject(ConnectionRegistry.java:332)
at org.nustaq.kontraktor.remoting.base.ActorClient$3.receiveObject(ActorClient.java:98)
at org.nustaq.kontraktor.remoting.base.ObjectSink.receiveObject(ObjectSink.java:38)
at org.nustaq.kontraktor.remoting.websockets.JSR356ClientConnector$WSClientEndpoint.onMessage(JSR356ClientConnector.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:142)
at io.undertow.websockets.jsr.FrameHandler$6.run(FrameHandler.java:245)
at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:162)
at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:159)
at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:575)
at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:561)
at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`

I assume you have the name of the field and the outer JSON element and everything in between. Any chance of dumping those in the trace output?

**Comment by RuedigerMoeller** [comment]
should be possible :)

**Comment by davidwynter** [comment]
A bit more info on this issue. I am now using Kontraktor 4.22. I looked thru all the classes that make up a fairly complex payload for the remote actor call and all implement Serializable, so am at a loss as to which class it is complaining about. I also note that it is saying the Actor$$Lambda$26/1188770185 is not Serializable? Is this really a fst problem, or is it a Kontraktor issue?
