### ISSUE TITLE
Deadlock in FSTClazzInfo.getAllFields

### ISSUE THREAD

**Issue by subes** [RuedigerMoeller/fast-serialization#234]
I tried using FST as the serialization provider for [JPPF](http://www.jppf.org/) but sadly I am encountering deadlocks when using the [remote classloader](http://www.jppf.org/doc/5.2/index.php?title=Class_loading_in_JPPF). My implementation can be found [here](https://github.com/subes/invesdwin-context-integration/blob/64eebb8706c58733aabc1ff471630011c3d38a91/invesdwin-context-integration-parent/invesdwin-context-integration-jppf/src/main/java/de/invesdwin/context/integration/jppf/internal/RemoteFastJPPFSerialization.java). There you can see I am using DefaultCoder and apply the remote classloader via FSTConfiguration.setClassloader(). Now during job deserialization, FST does its work and requests the first class from the remote classloader. This invokes some network traffic and the classes are transmitted in serialized form (via FST too). Now because the first deserialization thread (for the job) already has a static lock inside FSTClazzInfo.getAllFields() and the second deserialization thread (for the classloader response) also tries to get a static lock inside FSTClazzInfo.getAllFields(). This leads to the deadlock which seems to be caused by FST nested deserializations that are executed by different threads. See below for the full stacktraces.

```
"NodeForwarding-0007" #97 daemon prio=5 os_prio=0 tid=0x00007f944400c800 nid=0xf0a waiting for monitor entry [0x00007f9534ea8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.nustaq.serialization.FSTClazzInfo.getAllFields(FSTClazzInfo.java:240)
        - waiting to lock <0x00000005c03fbdc0> (a java.util.concurrent.ConcurrentHashMap)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:799)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:469)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:456)
        at org.nustaq.serialization.simpleapi.DefaultCoder.<init>(DefaultCoder.java:47)
        at org.nustaq.serialization.simpleapi.DefaultCoder.<init>(DefaultCoder.java:66)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$ConfDefaultCoder.<init>(RemoteFastJPPFSerialization.java:59)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$ConfDefaultCoder.<init>(RemoteFastJPPFSerialization.java:59)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$1.initialValue(RemoteFastJPPFSerialization.java:24)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$1.initialValue(RemoteFastJPPFSerialization.java:1)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
        at java.lang.ThreadLocal.get(ThreadLocal.java:170)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization.serialize(RemoteFastJPPFSerialization.java:33)
        at de.invesdwin.context.integration.jppf.internal.HighLZ4Serialization.serialize(HighLZ4Serialization.java:32)
        at org.jppf.comm.socket.BootstrapObjectSerializer.serialize(BootstrapObjectSerializer.java:89)
        at org.jppf.management.CustomWrapping2$WrappedObject.writeObject(CustomWrapping2.java:81)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at com.sun.jmx.remote.socket.SocketConnection.writeMessage(SocketConnection.java:318)
        at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendWithReturn(ClientSynchroMessageConnectionImpl.java:261)
        - locked <0x000000074951a9e0> (a [I)
        at javax.management.remote.generic.AbstractClientIntermediary.mBeanServerRequest(AbstractClientIntermediary.java:297)
        at javax.management.remote.generic.AbstractClientIntermediary.mBeanServerRequest(AbstractClientIntermediary.java:282)
        at javax.management.remote.generic.ClientIntermediary.invoke(ClientIntermediary.java:417)
        at javax.management.remote.generic.RemoteMBeanServerConnection.invoke(RemoteMBeanServerConnection.java:185)
        at org.jppf.management.JMXConnectionWrapper.invoke(JMXConnectionWrapper.java:282)
        - locked <0x0000000746808320> (a org.jppf.management.JMXNodeConnectionWrapper)
        at org.jppf.management.forwarding.InvokeMethodTask.execute(InvokeMethodTask.java:66)
        at org.jppf.management.forwarding.AbstractForwardingTask.call(AbstractForwardingTask.java:58)
        at org.jppf.management.forwarding.AbstractForwardingTask.call(AbstractForwardingTask.java:29)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x0000000751b5daf0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Processing-0003" #95 daemon prio=5 os_prio=0 tid=0x00007f948801e800 nid=0xf08 in Object.wait() [0x00007f95350a8000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000075621bfe8> (a java.lang.Object)
        at java.lang.Object.wait(Object.java:502)
        at org.jppf.classloader.ResourceFuture.get(ResourceFuture.java:95)
        - locked <0x000000075621bfe8> (a java.lang.Object)
        at org.jppf.classloader.ResourceFuture.get(ResourceFuture.java:32)
        at org.jppf.classloader.AbstractClassLoaderConnection.loadResource(AbstractClassLoaderConnection.java:121)
        at org.jppf.classloader.AbstractJPPFClassLoaderLifeCycle.loadResource(AbstractJPPFClassLoaderLifeCycle.java:157)
        at org.jppf.classloader.AbstractJPPFClassLoader.findClass(AbstractJPPFClassLoader.java:150)
        - locked <0x0000000741491120> (a org.jppf.classloader.JPPFLocalClassLoader)
        at org.jppf.classloader.AbstractJPPFClassLoader.findClass(AbstractJPPFClassLoader.java:110)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        - locked <0x0000000741491120> (a org.jppf.classloader.JPPFLocalClassLoader)
        at org.jppf.classloader.AbstractJPPFClassLoader.loadClass(AbstractJPPFClassLoader.java:332)
        - locked <0x0000000741491120> (a org.jppf.classloader.JPPFLocalClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredFields(Class.java:1916)
        at org.nustaq.serialization.FSTClazzInfo.getAllFields(FSTClazzInfo.java:249)
        - locked <0x00000005c03fbdc0> (a java.util.concurrent.ConcurrentHashMap)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:174)
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478)
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
        at org.nustaq.serialization.simpleapi.DefaultCoder.toObject(DefaultCoder.java:110)
        at org.nustaq.serialization.simpleapi.DefaultCoder.toObject(DefaultCoder.java:118)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization.deserialize(RemoteFastJPPFSerialization.java:50)
        at de.invesdwin.context.integration.jppf.internal.HighLZ4Serialization.deserialize(HighLZ4Serialization.java:41)
        at org.jppf.utils.ObjectSerializerImpl.deserialize(ObjectSerializerImpl.java:134)
        at org.jppf.utils.ObjectSerializerImpl.deserialize(ObjectSerializerImpl.java:122)
        at org.jppf.io.IOHelper.unwrappedData(IOHelper.java:230)
        at org.jppf.server.node.local.JPPFLocalContainer$ObjectDeserializationTask.call(JPPFLocalContainer.java:131)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x00000007414dd2a8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"JobExecutor_0007" #83 daemon prio=5 os_prio=0 tid=0x00007f949c003800 nid=0xef3 waiting for monitor entry [0x00007f953c730000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.nustaq.serialization.FSTClazzInfo.getAllFields(FSTClazzInfo.java:240)
        - waiting to lock <0x00000005c03fbdc0> (a java.util.concurrent.ConcurrentHashMap)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
        at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
        at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
        at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
        at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)
        at org.nustaq.serialization.simpleapi.DefaultCoder.toByteArray(DefaultCoder.java:90)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization.serialize(RemoteFastJPPFSerialization.java:34)
        at de.invesdwin.context.integration.jppf.internal.HighLZ4Serialization.serialize(HighLZ4Serialization.java:32)
        at org.jppf.comm.socket.BootstrapObjectSerializer.serialize(BootstrapObjectSerializer.java:89)
        at org.jppf.management.CustomWrapping2$WrappedObject.writeObject(CustomWrapping2.java:81)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at com.sun.jmx.remote.socket.SocketConnection.writeMessage(SocketConnection.java:318)
        at com.sun.jmx.remote.generic.ServerSynchroMessageConnectionImpl$RemoteJob.run(ServerSynchroMessageConnectionImpl.java:339)
        - locked <0x000000073e31a350> (a [I)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x000000073e31a558> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"JPPF NIO-0007" #70 daemon prio=5 os_prio=0 tid=0x00007f94bc068800 nid=0xe63 waiting for monitor entry [0x00007f9536be2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.nustaq.serialization.FSTClazzInfo.getAllFields(FSTClazzInfo.java:240)
        - waiting to lock <0x00000005c03fbdc0> (a java.util.concurrent.ConcurrentHashMap)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:799)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:469)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:456)
        at org.nustaq.serialization.simpleapi.DefaultCoder.<init>(DefaultCoder.java:47)
        at org.nustaq.serialization.simpleapi.DefaultCoder.<init>(DefaultCoder.java:66)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$ConfDefaultCoder.<init>(RemoteFastJPPFSerialization.java:59)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$ConfDefaultCoder.<init>(RemoteFastJPPFSerialization.java:59)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$1.initialValue(RemoteFastJPPFSerialization.java:24)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization$1.initialValue(RemoteFastJPPFSerialization.java:1)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
        at java.lang.ThreadLocal.get(ThreadLocal.java:170)
        at de.invesdwin.context.integration.jppf.internal.RemoteFastJPPFSerialization.serialize(RemoteFastJPPFSerialization.java:33)
        at de.invesdwin.context.integration.jppf.internal.HighLZ4Serialization.serialize(HighLZ4Serialization.java:32)
        at org.jppf.utils.ObjectSerializerImpl.serialize(ObjectSerializerImpl.java:79)
        at org.jppf.io.IOHelper.serializeDataToMemory(IOHelper.java:330)
        at org.jppf.io.IOHelper.serializeData(IOHelper.java:311)
        at org.jppf.server.nio.classloader.AbstractClassContext.serializeResource(AbstractClassContext.java:68)
        at org.jppf.server.nio.classloader.client.SendingProviderRequestState.performTransition(SendingProviderRequestState.java:85)
        at org.jppf.server.nio.classloader.client.SendingProviderRequestState.performTransition(SendingProviderRequestState.java:36)
        at org.jppf.nio.StateTransitionTask.run(StateTransitionTask.java:78)
        - locked <0x00000007479a0fa8> (a org.jppf.nio.SelectionKeyWrapper)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x000000073ebf4b58> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by subes** [comment]
I guess for now I will switch to the JDK serialization in JPPF until there is an idea on how to fix this issue.

**Comment by RuedigerMoeller** [comment]
you probably will need to turn of shared metadata (different classloaders)

**Comment by subes** [comment]
Can you tell me what I need to call to accomplish that? I will try it immediately.

**Comment by RuedigerMoeller** [comment]
the flag does not yet exist :)

**Comment by RuedigerMoeller** [comment]
`FSTClazzInfo.BufferConstructorMeta` and
`FSTClazzInfo.BufferFieldMeta` need to be set to false (works with 2.57 and above, in prior versions, the flag is respected but the lock is aquired anyway).

version 2.57 is checked in and will be available on maven central in ~ 2 to 12 hours

**Comment by subes** [comment]
Thanks a lot for the quick release. The deadlock is fixed now. Though would it be possible to configure/override this behavior for specific FSTConfiguration instances only and let the default stay on true for shared data?

On the other hand I cannot fully follow why the shared lock is actually needed inside `org.nustaq.serialization.FSTClazzInfo.getAllFields` since already there is a concurrent hashmap being used. Worst case without synchronization the map values would replaced rarely when two threads try to retrieve the data at the same time. Does not seem to be bad in my eyes since on the next request the data will be anyway loaded from the concurrent hashmap properly. Removing the shared lock completely would even lead to higher multithreaded throughput with the cache being enabled, wouldn't it?

At least getting rid of the lock would still keep my scenario working and allow me to keep the caches enabled.

**Comment by subes** [comment]
Just tested it and the combination:
FSTClazzInfo.BufferConstructorMeta = true
FSTClazzInfo.BufferFieldMeta = false

also works. FSTClazzInfo.BufferConstructorMeta usage inside `org.nustaq.serialization.FSTDefaultClassInstantiator.findConstructorForSerializable` is also just a share ConcurrentHashMap without a separate lock as suggested above for `org.nustaq.serialization.FSTClazzInfo.getAllFields`

**Comment by RuedigerMoeller** [comment]
if Constructors are shared amongst classloaders, errors might occur once different versions of the same class are actually loaded into the same VM ..

**Comment by subes** [comment]
ok, in that case it makes sense to disable this for the whole JVM

**Comment by RuedigerMoeller** [comment]
> On the other hand I cannot fully follow why the shared lock is actually needed inside org.nustaq.serialization.FSTClazzInfo.getAllFields since already there is a concurrent hashmap being used. Worst case without synchronization the map values would replaced rarely when two threads try to retrieve the data at the same time. 

locking is necessary as initially an incomplete list is put into the static hmap which can be seen by concurrent threads (was a real world issue in the past). The method needs to be rewritten such that the lisz is "published" once it is complete. However with ~20000 monthly downloads of >10000 distinct ip's i've become quite reluctant changes things without urge .. its easy to break things, especially regarding concurrency :)

**Comment by subes** [comment]
Well, with these infos I am happy with the solution provided. So thanks a lot for your hard work and fast responses :)
