### ISSUE TITLE
Class loader exeception

### ISSUE THREAD

**Issue by TheRedSpy15** [RuedigerMoeller/fast-serialization#239]
Exeception:
```
Exception in thread "Thread-368" java.lang.NoClassDefFoundError: org/objenesis/Objenesis
	at org.nustaq.serialization.FSTObjectOutput.<init>(FSTObjectOutput.java:85)
	at com.TheRedSpy15.trail.Gang.saveData(Gang.java:82)
	at com.TheRedSpy15.trail.Main.saveGameState(Main.java:166)
	at com.TheRedSpy15.trail.TravelController.lambda$TravelTask$2(TravelController.java:121)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.objenesis.Objenesis
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Note**: I'm using IntelliJ and have added the library as a jar/external library without the use of a build manager such as Maven or Gradle

Code where exeception is happening:

```
static void saveData() throws IOException {

        FileOutputStream fileOutputStream = new FileOutputStream("SaveGame.ser");
        FSTObjectOutput objectOutputStream = new FSTObjectOutput(fileOutputStream);

        objectOutputStream.writeObject(Main.gang);
        objectOutputStream.writeObject(Main.gang.gangMembers);
        objectOutputStream.writeObject(Main.gang.deceased);

        objectOutputStream.close();
        fileOutputStream.close();
    }
```

**Comment by RuedigerMoeller** [comment]
fst has some dependencies, check the releases tab for a all-included jar

**Comment by TheRedSpy15** [comment]
Little late on seeing this. I have decided to go with Gson instead of FST
