### ISSUE TITLE
Error generating the JSON

### ISSUE THREAD

**Issue by tosehee75** [RuedigerMoeller/fast-serialization#261]
Following error is generated when trying to convert the java class to JSON.

`com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._verifyPrettyValueWrite(JsonGeneratorImpl.java:234)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1056)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:316)
	at org.nustaq.serialization.coders.FSTJsonEncoder.writeTag(FSTJsonEncoder.java:284)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectHeader(FSTObjectOutput.java:744)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:446)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:319)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:275)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:193)
	at org.nustaq.serialization.FSTConfiguration.asByteArray(FSTConfiguration.java:1138)
	at org.nustaq.serialization.FSTConfiguration.asJsonString(FSTConfiguration.java:1184)
	at com.deposco.caching.RedisCacheManager.asJsonString(RedisCacheManager.java:207)
	at dep.config.RedisConfigDb.convertToSqlDescriptorIfNeeded(RedisConfigDb.java:212)
	at dep.config.RedisConfigDb.put(RedisConfigDb.java:127)
	at dep.config.ConfigBean.put(ConfigBean.java:600)
	at dep.config.ConfigParser.put(ConfigParser.java:148)
	at dep.config.ConfigParser.put(ConfigParser.java:128)
	at dep.controller.HandlerConfigParser.finishElement(HandlerConfigParser.java:138)
	at dep.config.SAXLoader.endElement(SAXLoader.java:312)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
`

**Comment by tosehee75** [comment]
private FSTConfiguration jsonConf = FSTConfiguration.createJsonConfiguration(true, false);

jsonConf is created within singleton class, and I am just calling jsonConf.asJsonString(value);

**Comment by RuedigerMoeller** [comment]
just provide a testcase please
