### ISSUE TITLE
Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gilshallem** [RuedigerMoeller/fast-serialization#265]
Hi, 
I get this error in Crashlitics

> Exception: java.lang.ArrayIndexOutOfBoundsException: length=2771273; regionStart=-1; regionLength=2771274
>        at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
>        at libcore.io.IoBridge.read(IoBridge.java:463)
>        at java.io.FileInputStream.read(FileInputStream.java:177)
>        at org.nustaq.serialization.FSTConfiguration.decodeFromStream(FSTConfiguration.java:1275)
>        at com.gilapps.smsshare2.theming.ThemesManager$2.call(ThemesManager.java:169)
>        at com.gilapps.smsshare2.theming.ThemesManager$2.call(ThemesManager.java:145)
>        at com.github.rongi.async.Task.run(Task.java:28)
>        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>        at java.lang.Thread.run(Thread.java:818)

please help

**Comment by RuedigerMoeller** [comment]
please provide a testcase :). looks more like a corrupted stream (huge array)
