### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by codeskraps** [RuedigerMoeller/fast-serialization#266]
`java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
	at org.nustaq.serialization.serializers.FSTMapSerializer.writeObject(FSTMapSerializer.java:44)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:476)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)
	at org.nustaq.serialization.FSTConfiguration.asByteArray(FSTConfiguration.java:1182)
	at org.gameyourgame.game.data.cache.CacheManager.lambda$writeObjectToFile$0(CacheManager.java:463)
	at org.gameyourgame.game.data.cache.-$$Lambda$CacheManager$NzZzbsSctWzhXYMul00zV5jbOI8.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)`

**Comment by RuedigerMoeller** [comment]
you cannot serialize a mutating data structure
