### ISSUE TITLE
Compatible with jdk11 

### ISSUE THREAD

**Issue by xingcxb** [RuedigerMoeller/fast-serialization#271]
Serializing an object directly fails

java.lang.RuntimeException: java.io.IOException: java.lang.NullPointerException
	at com.jfinal.plugin.redis.serializer.FstSerializer.valueFromBytes(FstSerializer.java:78)
	at com.jfinal.plugin.redis.Cache.valueFromBytes(Cache.java:1217)
	at com.jfinal.plugin.redis.Cache.get(Cache.java:91)

**Comment by tosehee** [comment]
Is this library flat out doesn't work with Java 9 and above????? 

If so, seems like a big deal to me. I'm evaluating this library, but if this is true, it's a total blow.

Especially when Java 12 just came out..

**Comment by RuedigerMoeller** [comment]
haven't had time, however i know some large projects tweaked it to work with jdk11.

**Comment by DanySK** [comment]
It's working for me out of the box, but raises runtime warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/home/travis/.gradle/caches/modules-2/files-2.1/de.ruedigermoeller/fst/2.57/70583ffcab07a0c756428811dd108a342b575d2e/fst-2.57.jar) to field java.math.BigDecimal.intVal
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by fgiannetti** [comment]
Same as @DanySK here

**Comment by ghost** [comment]
I believe with Java 9+ (tested with Java 11 and Java 17) the following works ...

#!/bin/bash
java \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.math=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.text=ALL-UNNAMED \
--add-opens=java.sql/java.sql=ALL-UNNAMED \
-jar [filename].jar

**Comment by DanySK** [comment]
Yeah, but fixing the illegal access (if possible) would be far better than opening modules from the CLI
