### ISSUE TITLE
Sometimes NullPointerException was throwed when deserialing my data

### ISSUE THREAD

**Issue by zhushanhu** [RuedigerMoeller/fast-serialization#276]
My code is
`private final FSTConfiguration fst = FSTConfiguration.createUnsafeBinaryConfiguration();
	
	@Override
	public byte[] toByteArray(Object object) {
		return fst.asByteArray(object);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public <T> T toObject(byte[] bytes, Class<T> clazz) {
		return (T)fst.asObject(bytes);
	}`

I use this code to encode/decode my data, it worked fine for me, but recently I got NullPointerException sometimes on my server. I can't find what is wrong, can you help me to find the reason? The serialized data is attacted. 
the version is 2.47
and the detail Exception is
`java.io.IOException: java.lang.NullPointerException
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
        at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1124)
        at com.huatai.ats.base.foundation.transport.serialization.FSTSerializer.toObject(FSTSerializer.java:30)
        at com.huatai.ats.base.foundation.service.persistence.PersistentDataSerializeHelper.getContext(PersistentDataSerializeHelper.java:85)
        at com.huatai.ats.base.foundation.service.persistence.AsyncPersistenceConsumer$ConsumerDelivery.dispatchData(AsyncPersistenceConsumer.java:133)
        at com.huatai.ats.base.foundation.service.persistence.AsyncPersistenceConsumer$ConsumerDelivery.deliver(AsyncPersistenceConsumer.java:75)
        at com.huatai.ats.base.foundation.transport.kafka.AbstractKafkaConsumer.consume(AbstractKafkaConsumer.java:198)
        at com.huatai.ats.base.foundation.transport.kafka.KafkaAtLeastOnceConsumer.invoke(KafkaAtLeastOnceConsumer.java:18)
        at com.huatai.ats.base.foundation.transport.kafka.AbstractKafkaConsumer.run(AbstractKafkaConsumer.java:179)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[1.zip](https://github.com/RuedigerMoeller/fast-serialization/files/2875235/1.zip)

        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException`

**Comment by zhushanhu** [comment]
I have got the reason, serialized data was broken for multi-thread access the object, thanks all the same.

**Comment by liangxiaowucai** [comment]
How fix this？
