### ISSUE TITLE
Runtime exception on deserialisation

### ISSUE THREAD

**Issue by pditommaso** [RuedigerMoeller/fast-serialization#296]
I'm getting the following exception while deserializing a class to which was added a field. 

```
java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@764c12b6
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.redisson.codec.FstCodec$1.decode(FstCodec.java:250)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:378)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:209)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:147)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
:
```

Is that expected or it's a bug? more what the best practice to evolve objects without breaking the ser/deser mechanism?

**Comment by pditommaso** [comment]
Yes, I've found that's the way to go.
