### ISSUE TITLE
throw NullPointerException when readObject

### ISSUE THREAD

**Issue by fangjinuo** [RuedigerMoeller/fast-serialization#304]
JDK : 1.8.0_152
test case: see the test case attachment

## exception stack

``` text
com.jn.agileway.codec.CodecException: java.io.IOException: java.lang.NullPointerException

	at com.jn.agileway.codec.fst.FstCodec.decode(FstCodec.java:26)
	at com.jn.agileway.codec.tests.CodecTests.testFst(CodecTests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.RuntimeException: java.io.IOException: java.lang.NullPointerException
	at com.jn.langx.util.Throwables.wrapAsRuntimeException(Throwables.java:93)
	at com.jn.agileway.codec.fst.Fsts.deserialize(Fsts.java:138)
	at com.jn.agileway.codec.fst.Fsts.deserialize(Fsts.java:121)
	at com.jn.agileway.codec.fst.FstCodec.decode(FstCodec.java:24)
	... 23 more
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at com.jn.agileway.codec.fst.Fsts.deserialize(Fsts.java:134)
	... 25 more
Caused by: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
	... 26 more

```

[fst-tests.zip](https://github.com/RuedigerMoeller/fast-serialization/files/5362854/fst-tests.zip)

**Comment by Traderjoe95** [comment]
I am experiencing the same issue, is there any update on that?

**Comment by fangjinuo** [comment]
> I am experiencing the same issue, is there any update on that?

https://github.com/fangjinuo/agileway
