### ISSUE TITLE
FST doesn't work on Java 16

### ISSUE THREAD

**Issue by Venorcis** [RuedigerMoeller/fast-serialization#312]
The following exception is always thrown:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @59690aa4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:504)
	at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:367)
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:128)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:97)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:84)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:80)
	at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:810)
	at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:477)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:472)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
```

This is probably related to the implementation of JEP-396...

**Comment by izogfif** [comment]
Temporary workaround: add `--illegal-access=permit` argument as a command-line argument for your `java.exe`. Yes, to `java.exe`, not to `javac` or compiler options. You can't tell this to compiler. You have to tell `--illegal-access=permit` to java executable.

**Comment by d98ama** [comment]
It seems like this workaround will no longer be possible with Java 17:

`OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0`

**Comment by mtf90** [comment]
Judging by the comments in projectlombok/lombok#2681 (especially the ones by @pron) granting (instrusive) access to internal classes and properties of JDK classes is to be explicitly white-listed by developers in the future. So issues like these probably won't magically disappear. However, the JVM seems to officially support granting these access rights via the `--add-opens` flags.

I managed to solve the above issue with the following maven config (we use FST during testing):


```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <argLine>--add-opens=java.base/java.lang=ALL-UNNAMED
            --add-opens=java.base/java.math=ALL-UNNAMED
            --add-opens=java.base/java.util=ALL-UNNAMED
            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
            --add-opens=java.base/java.net=ALL-UNNAMED
            --add-opens=java.base/java.text=ALL-UNNAMED
            --add-opens=java.sql/java.sql=ALL-UNNAMED</argLine>
    </configuration>
</plugin>
```

I wasn't able to check this with Java 17, but maybe this proves useful for somebody else as well.

**Comment by JJBRT** [comment]
You will solve with [**Burningwave Core reflection components**](https://github.com/burningwave/core#Handling-privates-and-all-other-members-of-an-object) that thanks to a [special driver](https://github.com/burningwave/jvm-driver#burningwave-jvm-driver-) work on all JDK [from 8 to 18-ea](https://github.com/burningwave/core/actions/runs/1224361768)

**Comment by JJBRT** [comment]
You will solve with [**Burningwave Core reflection components**](https://github.com/burningwave/core#Handling-privates-and-all-other-members-of-an-object) **without any JVM parameter** that thanks to a [special driver](https://github.com/burningwave/jvm-driver#burningwave-jvm-driver-) work on all JDK [from 8 to 18-ea](https://github.com/burningwave/core/actions/runs/1224361768)

**Comment by JJBRT** [comment]
You will solve **without any JVM parameter** with [**Burningwave Core reflection components**](https://github.com/burningwave/core#Handling-privates-and-all-other-members-of-an-object)  that thanks to a [special driver](https://github.com/burningwave/jvm-driver#burningwave-jvm-driver-) work on all JDK [from 8 to 18-ea](https://github.com/burningwave/core/actions/runs/1224361768)

**Comment by JJBRT** [comment]
It can be solved **without any JVM parameter** with [**Burningwave Core reflection components**](https://github.com/burningwave/core#Handling-privates-and-all-other-members-of-an-object)  that thanks to a [special driver](https://burningwave.github.io/jvm-driver/) work on all JDKs [from 8](https://dev.to/jjbrt/how-to-make-reflection-fully-work-on-jdk-16-and-later-ihp). In this case you can also simply call the method `org.burningwave.core.assembler.StaticComponentContainer.Modules.exportAllToAll()`

**Comment by RockyMM** [comment]
I would strongly advise against breaking strong encapsulation and going against what is mainstream Java orientation. `--add-opens` is only supported way to access Java internals. Anything else will create a maintenance burden and produce security concerns.

**Comment by Birthright50** [comment]
Will there be a solution to the problem out of the box or is the project abandoned?

**Comment by istinnstudio** [comment]
Strong Encapsulation in the JDK Java 17 LTS

It is a funtamental change for security reasons and probably will stay for ever. This probably means that "--add-opens=...." will follow all upgraded projects to 17 LTS.

https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-7744EF96-5899-4FB2-B34E-86D49B2E89B6

**Comment by oschina** [comment]
> Judging by the comments in [projectlombok/lombok#2681](https://github.com/projectlombok/lombok/issues/2681) (especially the ones by @pron) granting (instrusive) access to internal classes and properties of JDK classes is to be explicitly white-listed by developers in the future. So issues like these probably won't magically disappear. However, the JVM seems to officially support granting these access rights via the `--add-opens` flags.
> 
> I managed to solve the above issue with the following maven config (we use FST during testing):
> 
> ```
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-surefire-plugin</artifactId>
>     <configuration>
>         <argLine>--add-opens=java.base/java.lang=ALL-UNNAMED
>             --add-opens=java.base/java.math=ALL-UNNAMED
>             --add-opens=java.base/java.util=ALL-UNNAMED
>             --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
>             --add-opens=java.base/java.net=ALL-UNNAMED
>             --add-opens=java.base/java.text=ALL-UNNAMED
>             --add-opens=java.sql/java.sql=ALL-UNNAMED</argLine>
>     </configuration>
> </plugin>
> ```
> 
> I wasn't able to check this with Java 17, but maybe this proves useful for somebody else as well.

This solution works on Java 17 ！

**Comment by MatCuk** [comment]
Is there any plan to fix this as part of library update instead of adding maven configuration options?

**Comment by JJBRT** [comment]
> Is there any plan to fix this as part of library update instead of adding maven configuration options?

Take a look at [how to export all modules to all modules at runtime](https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m)

**Comment by debraj-manna** [comment]
In maven central I can see the below version. 

https://mvnrepository.com/artifact/de.ruedigermoeller/fst/3.0.4-jdk17

Does `3.0.4-jdk17` support JDK 17?

**Comment by istinnstudio** [comment]
The name points that it does, only after using the necessary"--add-opens" settings. Changes from the old version: https://github.com/RuedigerMoeller/fast-serialization/compare/master...jdk17

**Comment by pron** [comment]
@JJBRT Note that any remaining loophole in strong encapsulation, including JNI, will eventually also require an explicit command-line permission similar to add-opens -- just as SecurityManager required such permission -- as strong encapsulation gradually becomes the foundation of the JDK's security.

**Comment by debraj-manna** [comment]
> The name points that it does, only after using the necessary"--add-opens" settings. Changes from the old version: [master...jdk17](https://github.com/RuedigerMoeller/fast-serialization/compare/master...jdk17)

@istinnstudio - It is not related to fast-seralization. But if you have any suggestion on how to specify the `--add-opens` in a maven project? I have added the below settings to `maven-compiler-plugin`. But while executing the jar and running the tests. I am still getting the below error.

```
Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @7bb58ca3`. 
```

```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.10.1</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
          <!--https://stackoverflow.com/questions/46878649/maven-compilation-issue-with-java-9-->
          <showWarnings>true</showWarnings>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <!-- https://github.com/RuedigerMoeller/fast-serialization/issues/312 -->
            <arg>--add-opens</arg>
            <arg>java.base/java.lang=ALL-UNNAMED</arg>
            <arg>--add-opens</arg>
            <arg>java.base/java.math=ALL-UNNAMED</arg>
            <arg>--add-opens</arg>
            <arg>java.base/java.util=ALL-UNNAMED</arg>
            <arg>--add-opens</arg>
            <arg>java.base/java.util.concurrent=ALL-UNNAMED</arg>
            <arg>--add-opens</arg>
            <arg>java.base/java.net=ALL-UNNAMED</arg>
            <arg>--add-opens</arg>
            <arg>java.base/java.text=ALL-UNNAMED</arg>
            <arg>--add-opens</arg>
            <arg>java.sql/java.sql=ALL-UNNAMED</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```
