### ISSUE TITLE
FST doesn't work with GraalVM native-image

### ISSUE THREAD

**Issue by hamzajg** [RuedigerMoeller/fast-serialization#313]
Hello everyone.

Try to create a native image using GraalVM version 21.1.0 with Java 11.
But when running the native image, the following exception is always thrown:

```bash
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: [Ljava.lang.Object; (targetConstructorClass: java.lang.Object). Usually adding [Ljava.lang.Object; to serialization-config.json fixes the problem.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at com.oracle.svm.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:132)
	at jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:427)
	at sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:103)
	at org.nustaq.serialization.FSTDefaultClassInstantiator.findConstructorForSerializable(FSTDefaultClassInstantiator.java:110)
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:137)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
	at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:845)
	at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:478)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:473)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:465)
	at com.hamzajg.demo.fst.BootstrapApp.main(BootstrapApp.java:7)
```
Demo Example here:
https://github.com/vlingo/xoom-experimental/tree/fst-graalvm-demo/fst-graalvm-demo

Thanks..

**Comment by VaughnVernon** [comment]
Hallo, @hamzajg has a workaround for this problem, but it's far from ideal. We disallow serialization of `Object[]` and `byte[]`. It would be great to support all Java types and arrays.

We are happy to contribute the GraalVM implementation details so you can support it.

**Comment by imgoby** [comment]
I have the same problem, after compile under native-image,application run failed.
how to resolve.

```

java.lang.reflect.InaccessibleObjectException: Unable to make field private boolean java.lang.String.hashIsZero accessible: module java.base does not "opens java.lang" to unnamed module @7a4729e6
	at java.base@17.0.5/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base@17.0.5/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base@17.0.5/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base@17.0.5/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:504)
	at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:367)
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:128)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:97)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:84)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:80)
	at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:810)
	at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:477)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:472)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)

```

**Comment by imgoby** [comment]
the same problem in jdk 17

```
        <groupId>de.ruedigermoeller</groupId>
            <artifactId>fst</artifactId>
<version>3.0.4-jdk17</version
```>
