### ISSUE TITLE
can version 3.x  support java 8 ?

### ISSUE THREAD

**Issue by hapoy9** [RuedigerMoeller/fast-serialization#333]
can version 3.x  support java 8 ?
now, 2.57  has a error
java.lang.StackOverflowError
at org.nustaq.serialization.util.DefaultFSTInt2ObjectMap.size(DefaultFSTInt2ObjectMap.java:39)
at org.nustaq.serialization.util.DefaultFSTInt2ObjectMap.size(DefaultFSTInt2ObjectMap.java:39)
at org.nustaq.serialization.util.DefaultFSTInt2ObjectMap.size(DefaultFSTInt2ObjectMap.java:39)
at org.nustaq.serialization.util.DefaultFSTInt2ObjectMap.size(DefaultFSTInt2ObjectMap.java:39)

**Comment by jovany-wang** [comment]
maybe duplicate with https://github.com/RuedigerMoeller/fast-serialization/issues/275
