### ISSUE TITLE
Java 21 LTS java.lang.foreign

### ISSUE THREAD

**Issue by istinnstudio** [RuedigerMoeller/fast-serialization#346]
This is not a "real" issue, it is just a reminder that Java 21 LTS has changed the "preview" feature of the used memory API in branches 17 and 20. So we need a revision of source for Java 21 by using the finalized [java.lang.foreign] (https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/foreign/package-summary.html), hopefully [RuedigerMoeller](https://github.com/RuedigerMoeller)  will do magic again and introduce an updated 21 source branch using the final Foreign Memory Access API, replacing the non existent  jdk.incubator.foreign in 21 LTS. Also there is a naming conflict with janassist lib in FieldAccess at FSTStructFactory class.

**Comment by maximevdk-tidal** [comment]
Do you know if there there is a way to get it working on Java 21 while waiting for the changes?

**Comment by istinnstudio** [comment]
Compiled sources with java17 should work just fine with 21, only latest source needs update, there has been significant changes on java.lang.foreign, so jdk17/20 branch source is not compatible with java21 for compile from source

**Comment by lilianalillyy** [comment]
PR for java 21 based on the jdk20 branch: https://github.com/RuedigerMoeller/fast-serialization/pull/353

**Comment by sterlp** [comment]
Currently it doesn't really work with java 21:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @61f8bee4
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
	at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:504)
	at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:367)
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:128)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:97)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:84)
	at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:80)
	at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:811)
	at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:478)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:473)
	at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:465)
	at org.sterl.FooTest.test(FooTest.java:33)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by istinnstudio** [comment]
This PR Compiles ok on 21 and works ok for me on my personal modified 2.57 version. Those errors, I guess, have to do with reflection restrictions only, so you have to use an equivalent --addopens argument when using the compiled jar. This should happen on any java version above 17
