### ISSUE TITLE
Empty ClassNotFoundException

### ISSUE THREAD

**Issue by hetzge** [RuedigerMoeller/fast-serialization#48]
I have a big problem with the library which is not very transparent for me. Here the exception i get in diffrent situations:
> 
Exception in thread "main" de.hetzge.sgame.common.exception.NetworkException: java.io.IOException: java.lang.RuntimeException: CLASSNAME:
	at de.hetzge.sgame.network.Client.connect(Client.java:47)
	at de.hetzge.sgame.network.NetworkModule.update(NetworkModule.java:36)
	at de.hetzge.sgame.application.ModulePool.update(ModulePool.java:30)
	at de.hetzge.sgame.application.Application.update(Application.java:27)
	at de.hetzge.sgame.application.Application.start(Application.java:17)
	at de.hetzge.sgame.game.Client.main(Client.java:32)
Caused by: java.io.IOException: java.lang.RuntimeException: CLASSNAME:
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:242)
	at de.hetzge.sgame.common.serializer.Serializer.deserialize(Serializer.java:35)
	at de.hetzge.sgame.network.Connection.read(Connection.java:26)
	at de.hetzge.sgame.network.Client.connect(Client.java:36)
	... 5 more
Caused by: java.lang.RuntimeException: CLASSNAME:
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:212)
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:183)
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:166)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:422)
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:855)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:340)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:358)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
	at org.nustaq.serialization.serializers.FSTCollectionSerializer.instantiate(FSTCollectionSerializer.java:90)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:461)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:356)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:358)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
	at org.nustaq.serialization.serializers.FSTCollectionSerializer.instantiate(FSTCollectionSerializer.java:90)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:461)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:356)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:659)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:517)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:358)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:306)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:240)
	... 8 more
Caused by: java.lang.ClassNotFoundException: 
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190)
	... 33 more
>

The classname of the class which is not found is empty. I think the reason for the exception ist something else. The application sends objects over the network and deserialize them with the library. The error happens if  i send more then a special amount of objects. If i send 10 objects (packed in a collection) it works fine. But if i increase to say 50 objects the error happens. All changed is the amount of the objects which are created the same way.

Here are my serialize methods:
```Java
public static byte[] serialize(Object object) throws IOException {
		FSTObjectOutput objectOutput = CommonConfig.INSTANCE.fst.getObjectOutput();
		objectOutput.writeObject(object);

		ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
		byteArrayOutputStream.write(objectOutput.getBuffer(), 0, objectOutput.getWritten());

		byte[] byteArray = byteArrayOutputStream.toByteArray();
		byteArrayOutputStream.close();
		return byteArray;
	}

	public static Object deserialize(byte[] bytes) throws IOException, ClassNotFoundException {
		ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes);
		FSTObjectInput objectInput = CommonConfig.INSTANCE.fst.getObjectInput(byteArrayInputStream);
		Object readObject = objectInput.readObject();
		byteArrayInputStream.close();
		return readObject;
	}
```

Here the code i use for the network communication:
````Java
public class Connection {

	private final Socket socket;
	private final DataOutputStream dataOutputStream;
	private final DataInputStream dataInputStream;

	public Connection(Socket socket) throws IOException {
		this.socket = socket;
		this.dataOutputStream = new DataOutputStream(socket.getOutputStream());
		this.dataInputStream = new DataInputStream(socket.getInputStream());
	}

	public Object read() throws IOException, ClassNotFoundException {
		int length = this.dataInputStream.readInt();
		byte[] byteArray = new byte[length];
		this.dataInputStream.read(byteArray);
		return Serializer.deserialize(byteArray);
	}

	public void write(Object message) throws IOException {
		byte[] serialized = Serializer.serialize(message);
		this.dataOutputStream.writeInt(serialized.length);
		this.dataOutputStream.write(serialized);
		this.dataOutputStream.flush();
	}

}
```

It looks like registering the classes allows a higher amount of classes.

Any idea what i am doing wrong ? 
... or are more informations needed ?

**Comment by RuedigerMoeller** [comment]
this happens if the stream is corrupted:

possible reasons:
- if you stream objects, first write length then object array, you cannot deserialize if only parts of objects have been received. see https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/net/TCPObjectSocket.java and the server class
- by incorrect multithreading
- you need to register classes on sender side and receiverside identically and in same order
- consider using **TCPObjectSocket, TCPObjectServer** delivered with fst. If this does not fit, see how i always write length of a message as a header. This way i can decode once i am sure the full message is received. Reason is, I can't go down all the wrapped streams of jdk for each byte read (very slow), so stream must be read in chunks of one serialized object

Your use of fst is quite inefficient, simplify:
- use utils FSTConfiguration.asByteArray, asObject to get rid of bytearraystreams (SLOW).
- remove classregistering for debug. once stuff runs, add it again. class registering is a very easy and effective opzimization, but must be symmetric sender/receiver.
- ensure you use latest version

**Comment by hetzge** [comment]
Very big thanks for the detailed and fast answer. When i use the TCPObjectSocket class my problem is blown away. 

You could throw a more meaningful exception and refer the TCPObjectSocket class in the "How to use Serialization" page in the wiki.

**Comment by RuedigerMoeller** [comment]
:-) i already updated the wiki, as there where other persons having similar issues .. throwing other exceptions is not too easy, as if stream is corrupted (or just plain 0,0,0,..) anything can fail during decode .. i'll try though. Thanx for reporting
