### ISSUE TITLE
Bouncycastle RSA Keypair

### ISSUE THREAD

**Issue by nicoruti** [RuedigerMoeller/fast-serialization#52]
First of all, thanks for this great serializer! I'm using it for every project I find a reason for because it is one of the best and most convenient one.

Today, I updated to the newest version (2.19) and also switched to the latest BouncyCastle version (bcprov-jdk15on:1.51). Serializing and deserializing a keypair generated with bouncy castle provider seems to run into an error. For your convenience, I created a <a href="https://gist.github.com/nicoruti/996995dacb97990d6db8">Github Gist here</a>.

Do I need to use a custom serializer to prevent this error (i.e. serializing keypairs manually)? Thanks for your help in advance!

**Comment by RuedigerMoeller** [comment]
Thanks for report and reproducer .. A custom serializer would be last resort/workaround. However as I aim for full JDK-serialization compatibility, I'll try to fix this as soon I find time.

**Comment by RuedigerMoeller** [comment]
fixed with 2.20 at cost of tagging each object written using ancient JDK methodology (+1 byte per class, superclass, supersuperclass, ..). 
For high performance do not use readObject/writeObject machinery or replace it by registering a custom serializer.

**Comment by RuedigerMoeller** [comment]
As GitHub apparently lost my initial analysis (multiple browsers windows), repeated analysis:

How to not implement serialization from bcastle BCRSAPublicKey.java:

```java
    private void readObject(
        ObjectInputStream in)
        throws IOException, ClassNotFoundException
    {
        in.defaultReadObject();

        try
        {
            algorithmIdentifier = AlgorithmIdentifier.getInstance(in.readObject());
        }
        catch (OptionalDataException e)
        {
            algorithmIdentifier = DEFAULT_ALGORITHM_IDENTIFIER;
        }
        catch (EOFException e)
        {
            algorithmIdentifier = DEFAULT_ALGORITHM_IDENTIFIER;
        }
    }

    private void writeObject(
        ObjectOutputStream out)
        throws IOException
    {
        out.defaultWriteObject();

        if (!algorithmIdentifier.equals(DEFAULT_ALGORITHM_IDENTIFIER))
        {
            out.writeObject(algorithmIdentifier.getEncoded());
        }
    }
```

a) writes 1 or 2 objects, but attempts to read always 2, then recovers using exceptions.
b) relying on exception catch as default execution path is extremely slow.
c) if the ongoing stream contains a byte sequence making up a valid object, this might fail (no exception thrown) in rare cases. 
d) Maybe a vulnerability as it is possible to inject a different algorithm by manipulating the stream data.

Consider filing an issue to bcastle. This is bad code.

**Comment by nicoruti** [comment]
You're awsome, thanks for this fast fix! It is indeed a dirty hack by bouncy castle. I filed an issue <a href="http://www.bouncycastle.org/jira/browse/BJA-525">here</a>.

**Comment by bcgit** [comment]
Diletant code would more likely be organised on the basis that no-one anywhere was already serialising keys with a widely used API and without any regard for that user base. It will be about 4 years before it is safe to try removing the if from the writeObject. Having said that for JCE/JCA keys I'd strongly recommend using something built around getEncoded(), aside from the other issues with Java serialisation you would at least get some level of provider independence.

**Comment by RuedigerMoeller** [comment]
never min my harsh comment. looks line you ran into the versioning trap. many fail taking this into account in advance, though its possible :)

**Comment by nicoruti** [comment]
@RuedigerMoeller does your I52 test work? My code posted in the Gist (first post) still fails with the following error:
```
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.util.FSTUtil.rethrow(FSTUtil.java:122)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:875)
	at TestSerializeKeyFST.main(TestSerializeKeyFST.java:35)
Caused by: java.io.IOException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:873)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.util.FSTUtil.rethrow(FSTUtil.java:122)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:564)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:526)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:511)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:359)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:660)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:518)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:359)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:326)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:561)
	... 11 more
Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Constructor.getParameterCount()I
	at org.nustaq.serialization.FSTObjectInput$2.readObjectOverride(FSTObjectInput.java:930)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:364)
	at org.nustaq.serialization.FSTObjectInput$MyObjectStream.readObjectOverride(FSTObjectInput.java:1246)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:364)
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPublicKey.readObject(Unknown Source)
	... 16 more
```
I'm using v2.20 over maven.

**Comment by RuedigerMoeller** [comment]
i added a test case. as the optionaldataexception has no public constructor, i instantiate it using reflection which seems to fail for you. which jdk do you use, i think i tested jdk 8

**Comment by RuedigerMoeller** [comment]
arg, i use jdk8 api ? i am at airport heathrow currently, will check back tomorrow ..

**Comment by nicoruti** [comment]
No need to hurry! :) i'm using jdk 7u71.

**Comment by RuedigerMoeller** [comment]
I won't have time for that until weekend ..
From the exception I assume that I use JDK8 API. If you have a fork your can fix it by porting 
https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTObjectInput.java the exception construction starting a line 925 to 1.7 API. Though the OptionalDataExcpetion is part of the püublic JDK serialization spec, it has no public constructor, so a competing implementation requires reflection + tweaks in order to create an throw it ..

The I52 testcase worked with JDK1.8 for me.

**Comment by nicoruti** [comment]
Great work! Works like a charm! Thanks!
