### ISSUE TITLE
[Android] sun.misc.Unsafe not fully supported

### ISSUE THREAD

**Issue by nicoruti** [RuedigerMoeller/fast-serialization#53]
Although stated as Android compatible, I ran into an exception today:
```
java.lang.RuntimeException: java.io.IOException: java.lang.RuntimeException: java.lang.NoSuchMethodError: sun.misc.Unsafe.putBoolean
            at org.nustaq.serialization.util.FSTUtil.rethrow(FSTUtil.java:122) ~[na:0.0]
            at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:875) ~[na:0.0]
            at org.hive2hive.core.security.FSTSerializer.deserialize(FSTSerializer.java:59) ~[na:0.0]
            at org.hive2hive.core.security.H2HDefaultEncryption.decryptAES(H2HDefaultEncryption.java:43) ~[na:0.0]
            at org.hive2hive.core.network.data.vdht.EncryptedVersionManager.get(EncryptedVersionManager.java:178) ~[na:0.0]
            at org.hive2hive.core.network.data.UserProfileManager$QueueWorker.run(UserProfileManager.java:203) ~[na:0.0]
            at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
     Caused by: java.io.IOException: java.lang.RuntimeException: java.lang.NoSuchMethodError: sun.misc.Unsafe.putBoolean
            at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:240) ~[na:0.0]
            at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:873) ~[na:0.0]
    ... 5 common frames omitted
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: sun.misc.Unsafe.putBoolean
            at org.nustaq.serialization.util.FSTUtil.rethrow(FSTUtil.java:122) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:304) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:238) ~[na:0.0]
    ... 6 common frames omitted
    Caused by: java.lang.NoSuchMethodError: sun.misc.Unsafe.putBoolean
            at org.nustaq.serialization.FSTClazzInfo$FSTFieldInfo.setBooleanValue(FSTClazzInfo.java:858) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:634) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:515) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:356) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:657) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:515) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:356) ~[na:0.0]
            at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:323) ~[na:0.0]
    ... 8 common frames omitted
```

Unfortunately, the <a href="https://android.googlesource.com/platform/libcore/+/master/libart/src/main/java/sun/misc/Unsafe.java">Unsafe implementation of Android</a> is incomplete and not all methods are available.

I tested with FST v.2.21 and Android 4.4.4. For the compilation, Android Studio with Java 7u71 is used.

**Comment by RuedigerMoeller** [comment]
actually i never tested it myself but merged a pull request. Actually there should be fallback code in case Unsafe is not avaiable. Apparantly, unsafe is avaiable but lacks some methods.
Could you retry by setting FSTUtil.unflaggedUnsafe = null; before actually serializing anything ?

**Comment by RuedigerMoeller** [comment]
Just ran some tests with FSTUtil.unflaggedUnsafe = null; .. ofc the offheap stuff does not work, but serialization tests passed. You might need to add some empty Default constructors in rare cases as without unsafe its sometimes impossible to construct an instance properly (however for Android, instantiation is delegated to objenesis anyway).

**Comment by nicoruti** [comment]
With setting <code>FSTUtil.unFlaggedUnsafe = null;</code>, I get
```
java.lang.NullPointerException: null
	at org.nustaq.serialization.FSTClazzInfo$FSTFieldInfo.getObjectValue(FSTClazzInfo.java:767) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:632) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:523) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:442) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:317) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:282) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:191) ~[fst-2.21.jar:na]
	at org.nustaq.serialization.FSTConfiguration.asByteArray(FSTConfiguration.java:885) ~[fst-2.21.jar:na]
	at org.hive2hive.core.security.FSTSerializer.serialize(FSTSerializer.java:61) ~[classes/:na]
```

I send a serialized object from a computer (normal JVM) to an Android device (Dalvik JVM). The exception occurs already at the sender and though is not JVM-specific. Is it possible to set the unFlaggedUnsafe only at the Android?

**Comment by RuedigerMoeller** [comment]
a) 
you need to set FSTUtil.unFlaggedUnsafe to null before accessing FSTConfiguration (put right in main). If FSTClazzinfo is constructed before FSTUtil.unFlaggedUnsafe = null, the check will fail as memoffset is intialized.

(FSTClazzInfo.java)
```java
        public final Object getObjectValue(Object obj) throws IllegalAccessException {
            if (memOffset >= 0) {  // <== true if unFlaggedUnsafe was set upon construction of FSTClazzinfo
                return FSTUtil.unFlaggedUnsafe.getObject(obj, memOffset);
            }
            return field.get(obj);
        }
```
b) yes, its possible to write with unsafe and read without.

**Comment by nicoruti** [comment]
Setting unFlaggedUnsafe to null before the configuration is created was the trick. However, I ran into another issue which does not correlate with FST itself. BouncyCastle does not seamlessly work on Android, therefore, when decoding the BouncyCastle keys, a transformation to SpongyCastle keys is required.
I created a custom serializer where the security provider can be injected:
```
public class FSTKeyPairSerializer extends FSTBasicObjectSerializer {

		private final String securityProvider;

		public FSTKeyPairSerializer(String securityProvider) {
			this.securityProvider = securityProvider;
		}

		@Override
		public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTFieldInfo referencedBy,
				int streamPosition) throws IOException {
			KeyPair keyPair = (KeyPair) toWrite;
			out.writeInt(keyPair.getPrivate().getEncoded().length);
			out.write(keyPair.getPrivate().getEncoded());

			out.writeInt(keyPair.getPublic().getEncoded().length);
			out.write(keyPair.getPublic().getEncoded());
		}

		@Override
		public void readObject(FSTObjectInput in, Object toRead, FSTClazzInfo clzInfo, FSTFieldInfo referencedBy)
				throws IOException, ClassNotFoundException, IllegalAccessException, InstantiationException {
			// do nothing
		}

		@Override
		public Object instantiate(Class objectClass, FSTObjectInput in, FSTClazzInfo serializationInfo,
				FSTFieldInfo referencee, int streamPositioin) throws IOException, ClassNotFoundException,
				InstantiationException, IllegalAccessException {
			try {
				byte[] buffer = new byte[in.readInt()];
				in.read(buffer);
				KeyFactory gen = KeyFactory.getInstance("RSA", securityProvider);
				PrivateKey privateKey = gen.generatePrivate(new PKCS8EncodedKeySpec(buffer));

				buffer = new byte[in.readInt()];
				in.read(buffer);
				PublicKey publicKey = gen.generatePublic(new X509EncodedKeySpec(buffer));
				return new KeyPair(publicKey, privateKey);
			} catch (NoSuchAlgorithmException | NoSuchProviderException | InvalidKeySpecException e) {
				logger.error("Failed to decode a keypair using a custom FST serializer", e);
				return super.instantiate(objectClass, in, serializationInfo, referencee, streamPositioin);
			}
		}
	}
```

In case of BouncyCastle, the security provider "BC" can be installed and used, in case of SpongyCastle "SC" can be installed and used.

**Comment by nicoruti** [comment]
Did look at the stack trace again and realized that it's obvious that the error occurs in the BitSet. I indeed serialize a class containing a BitSet in Android and send it over to a "normal" JVM, where the deserialization fails. For completeness, here are the two classes:
- <a href="https://android.googlesource.com/platform/libcore.git/+/master/luni/src/main/java/java/util/BitSet.java">Android BitSet</a>
- <a href="http://www.docjar.com/html/api/java/util/BitSet.java.html">Open JDK Bitset</a>

Identifying and remapping all these differences between the Dalvik/Android JVM and the "normal" JVM is really a pain... Unfortunately, I did not find a useful list / comparison in the Internet.

**Comment by RuedigerMoeller** [comment]
arg .. next problem. I'll again check if can be solved generically, else another custom serializer could be required. It might be a paint, however there are only few classes making use of ancient serialization machinery, so probably only like 4-6 classes of JDK will be problematic..

**Comment by RuedigerMoeller** [comment]
Its again the (unspecified afaik) assumption defaultRead/WriteObject produces exactly the same binary output as "putField". Should be fixable, I actually only have handled "asymetric read write" for real world cases as its kind of a pretty big matrix of how one can mix up reading + writing objects.

**Comment by RuedigerMoeller** [comment]
merged pr + fixed BitSet Issue with 2.22.

**Comment by nicoruti** [comment]
Thanks for your fast fixes! When are you planning to release version 2.22?

**Comment by RuedigerMoeller** [comment]
I actually uploaded it yesterday evening .. seems like something went wrong .. I'll check back this evening as I cannot relaese from office.

**Comment by RuedigerMoeller** [comment]
ah .. checke back. I released fast-cast 3.08 again :-) (wrong script started). Check back tomorrow or just clone and run mvn install (consider disabling tests)

**Comment by RuedigerMoeller** [comment]
upload underway, should be on maven org in some hours

**Comment by iamironz** [comment]
Guys you can see android `sun.misc.Unsafe` contract in my repo https://github.com/iamironz/unsafe
