### ISSUE TITLE
Serialize in 1.63 -> Deserialize in 2.24

### ISSUE THREAD

**Issue by MLWiDA** [RuedigerMoeller/fast-serialization#62]
First of all: Thank you very much for this fast and easy to use library !

I apologize beforehand if this question is dumb or unnecessary or should be asked somewhere else. I did not find anything in this regard (in release notes, wiki or stackoverflow).

_General question:_ Is the deserialization with version 2.24 of data serialized with 1.63 supported ? What should I be aware of ? If not supported, what is the recommended way to migrate ?

_Specific question (if it makes sense to address it)_
I have a lot of data serialized and stored with 1.63 and now want to upgrade. The error I get upon trying to deserialize is weird (I have serialized an instance of class A which contains an instance of class B (and something more), but deserialization returns an instance of class B. Since this code is very dependency-heavy, I have tried to reproduce it in a simpler way. I ended up with the snippet below, but I cannot make any sense of the different error I get now (Java 1.7 is used).

```
Caused by: java.lang.RuntimeException: unable to encodeValue class from code 87
    at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173)
    at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:431)
    at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:853)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:338)
    at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:323)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:304)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:238)
    ... 3 more
```

Thank you for your time 

_Da Code_
(Apologies for the byte-Array-mess ;), did only see recently the methods fst provide for that)

``` java
package de.steffen;

import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;

import de.ruedigermoeller.serialization.FSTConfiguration;
import de.ruedigermoeller.serialization.FSTObjectInput;
import de.ruedigermoeller.serialization.FSTObjectOutput;

public class MyFstSerializer
{

    public static class AClass implements Serializable
    {

        /**
         * 
         */
        private static final long serialVersionUID = -2808132944334495478L;

    }

    private final FSTConfiguration conf;

    /**
     * Initialize with considered-to-be-optimal configuration
     */
    public MyFstSerializer()
    {
        conf = FSTConfiguration.createDefaultConfiguration();
        @SuppressWarnings("rawtypes")
        List<Class> classesToRegister = new LinkedList<Class>();
        classesToRegister.add(AClass.class);

        conf.registerClass(classesToRegister.toArray(new Class[classesToRegister.size()]));
    }

    public AClass deserialize(byte[] data) throws IOException
    {
        AClass csc = null;
        final ByteArrayInputStream bais = new ByteArrayInputStream(data);
        final FSTObjectInput in = new FSTObjectInput(bais, conf);

        try
        {

            Object obj = conf.asObject(data);
            csc = (AClass) obj;
        } catch (final ClassCastException cnfe)
        {
            // cannot happen
            throw new RuntimeException(cnfe);
        } catch (Exception e)
        {
            // cannot happen
            throw new RuntimeException(e);
        } finally
        {
            in.close();
        }

        return csc;
    }

    public byte[] serialize(AClass csc) throws IOException
    {
        final ByteArrayOutputStream bos = new ByteArrayOutputStream();
        final FSTObjectOutput out = new FSTObjectOutput(bos, conf);
        byte[] data = null;
        try
        {
            out.writeObject(csc);
            out.flush();
            data = bos.toByteArray();
        } finally
        {
            out.close();
            bos.close();
        }
        if (data != null)
        {
            return data;
        } else
        {
            return null;
        }
    }

    public static byte[] loadByteArray(final String path) throws IOException
    {
        final File file = new File(path);
        final FileInputStream fin = new FileInputStream(file);
        final byte fileContent[] = new byte[(int) file.length()];
        try
        {
            fin.read(fileContent);
        } finally
        {
            fin.close();
        }
        return fileContent;
    }

    public static void saveByteArray(final byte[] data, final String path) throws IOException
    {
        final BufferedOutputStream out = new BufferedOutputStream(new FileOutputStream(path));
        try
        {
            out.write(data);
        } finally
        {
            out.close();
        }
    }

    public static void main(String[] args) throws Exception
    {
        // serialize with 1.63
        // then switch to 2.24, adjust imports and try deserialization
        MyFstSerializer serializer = new MyFstSerializer();
        AClass a = new AClass();
        byte[] data = serializer.serialize(a);

        saveByteArray(data, "/tmp/AClass163.ser");

        byte[] reloadedData = loadByteArray("/tmp/AClass163.ser");
        AClass reloadedA = serializer.deserialize(reloadedData);
    }

}
```

**Comment by RuedigerMoeller** [comment]
Unfortunately the binary format of 2.x is somewhat different (versioning, decoder layer) so there is no way to read 1.x streams with 2.x .

Best option is to upgrade all to 2.x.

Second option is to run 1.x and 2.x concurrently as they have completely different package names. You then somehow need to distinguish 1.x clients / files from 2.x clients / files. In your case you can also run kind of a conversion this way (read with 1.x, re-write with 2.x).

Generally spoken, supporting arbitrary backward compatibility would require a lot of tagging + checks dragging down performance and compactness. In addition this would introduce a lot of boring work on my side :) .

**Comment by MLWiDA** [comment]
I understand. Thank you very much for the fast reply :) :+1:

**Comment by RuedigerMoeller** [comment]
reopened to serve as FAQ :)

**Comment by jteagles** [comment]
What are the implications for hard coding a 2.24 class code in 2.50 registry to enable backwards compatibility with 2.24. 
```java
    FSTConfiguration fstConf = FSTConfiguration.createDefaultConfiguration();
    FSTClazzNameRegistry registry = fstConf.getClassRegistry();
    // Mod the class registry to be able to translate 2.24 LinkedHashMap to 2.50 LinkedHashMap
    registry.registerClass(LinkedHashMap.class, 83, fstConf);

    // Create an object to serialize
    HashMap<String, Object> root = new LinkedHashMap<String, Object>();
    ArrayList<Object> level1 = new ArrayList<Object>();
    HashMap<String, Object> level2 = new LinkedHashMap<String, Object>();
    level2.put("level2key", "level2value");
    level1.add(level2);
    root.put("level1key", level1);

    // Get the bytes for 2.50
    byte [] bytes = fstConf.asByteArray(root);
    // The bytes in 2.24
    byte [] bytes_224 = {0,1,23,106,97,118,97,46,117,116,105,108,46,76,105,110,107,101,100,72,97,115,104,77,97,112,1,-4,9,108,101,118,101,108,49,107,101,121,0,16,1,0,83,1,-4,9,108,101,118,101,108,50,107,101,121,-4,11,108,101,118,101,108,50,118,97,108,117,101};

    // Decode 2.50 bytes to object and test
    HashMap<String, Object> hm = (HashMap<String, Object>)fstConf.asObject(bytes);
    System.out.println(((LinkedHashMap)((ArrayList)hm.get("level1key")).get(0)).get("level2key"));

    // Decode 2.24 bytes to object and test
    HashMap<String, Object> hm_224 = (HashMap<String, Object>)fstConf.asObject(bytes_224);
    System.out.println(((LinkedHashMap)((ArrayList)hm_224.get("level1key")).get(0)).get("level2key"));
```

**Comment by RuedigerMoeller** [comment]
severe. allocating a fixed class id might create collisions. In addition there might be subtle changes in the bytes written by an object.

As fst currently does not support versioning intrinsically, shading an older fst version is the best and safest option. (e.g. rename fst package to ...fst224 in intellij and use the old version to read old objects).

starting from 2.48 class id's have been changed (0..1000 = fst predefined ids) > 1000 = dynamically assigned class ids. In previous versions all id's where assigned dynamically (starting from 3 or so), so adding a predefined class id in FSTConfiguration resulted in a compatibility break. This has been improved in 2.48.
