### ISSUE TITLE
When serialize HashSet<Long>, can I set the setShareReferences to false?

### ISSUE THREAD

**Issue by lcy2008a** [RuedigerMoeller/fast-serialization#67]
I use fst 2.27 and this is my test code:
```
        Set<Long> obj = new LinkedHashSet<>();
        obj.add(11373L);
        FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        conf.setShareReferences(false);
        byte[] bytes = conf.asByteArray(obj);
        Object o = conf.asObject(bytes);
```
When I run this, it throws following exception:
```
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.util.FSTUtil.rethrow(FSTUtil.java:114)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:879)
	at com.a17zuoye.commons.cache.TestFst.main(TestFst.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.IOException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:877)
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.util.FSTUtil.rethrow(FSTUtil.java:114)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:563)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:549)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:525)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:510)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:357)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:324)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:305)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:239)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:560)
	... 14 more
Caused by: java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 27
	at org.nustaq.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:995)
	at org.nustaq.serialization.FSTObjectInput$MyObjectStream.defaultReadObject(FSTObjectInput.java:1281)
	at java.util.HashSet.readObject(HashSet.java:294)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:278)
	at org.nustaq.serialization.FSTObjectInput$2.readByte(FSTObjectInput.java:1148)
	at org.nustaq.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:970)
	... 21 more
```
If I remove 'conf.setShareReferences(false);', it works. So if I mis-used this method or is this a bug? 

Thank you in advance for your kind help.

**Comment by RuedigerMoeller** [comment]
Thanks for reporting ! Probably a bug, testcases cover only default settings ..

**Comment by RuedigerMoeller** [comment]
seems its a bug only in the Utility methods of FSTConfiguration. If I manually serialize, ti seems to work:

```java
    @Test // works
    public void testUnsharedStream() throws IOException {
        Set<Long> obj = new LinkedHashSet<>();
        obj.add(11373L);
        FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        conf.setShareReferences(false);
        FSTObjectOutputNoShared fout = new FSTObjectOutputNoShared();
        fout.writeObject(obj);
        byte[] bytes = fout.getCopyOfWrittenBuffer();
        Object o = conf.asObject(bytes);
    }

    @Test // works
    public void testUnsharedStream1() throws IOException {
        Set<Long> obj = new LinkedHashSet<>();
        obj.add(11373L);
        FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        conf.setShareReferences(false);
        FSTObjectOutput fout = new FSTObjectOutput();
        fout.writeObject(obj);
        byte[] bytes = fout.getCopyOfWrittenBuffer();
        Object o = conf.asObject(bytes);
    }

    @Test // FAILS !!
    public void testUnshared() {
        Set<Long> obj = new LinkedHashSet<>();
        obj.add(11373L);
        FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        conf.setShareReferences(false);
        byte[] bytes = conf.asByteArray(obj);
        Object o = conf.asObject(bytes);
    }
```

**Comment by RuedigerMoeller** [comment]
Got it (first analysis deleted as wrong). This is a known restriction: JDK Emulation only works for shared streams. This means only serializable, externalizable classes will work. readObject/writeObject/readReplace are not supported. You'd have to supply a custom serializer for LinkedHashSet, as LinkedHashSet uses old-school JDK mechanics.

from FSTObjectInputNoShared:
```java
/**
 * Subclass optimized for "unshared mode". Cycles and Objects referenced more than once will not be detected.
 * Additionally JDK compatibility is not supported (read/writeObject and stuff). Use case is highperformance
 * serialization of plain cycle free data (e.g. messaging). Can perform significantly faster (20-40%).
 */
```
this comment should also be present in setShared method.

**Comment by RuedigerMoeller** [comment]
this one works then:
```java
@Test
    public void testUnshared() {
        Set<Long> obj = new LinkedHashSet<>();
        obj.add(11373L);
        FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        conf.setShareReferences(false);
        conf.registerSerializer(LinkedHashSet.class,new FSTCollectionSerializer(),true);
        byte[] bytes = conf.asByteArray(obj);
        Object o = conf.asObject(bytes);
    }
```
