### ISSUE TITLE
NullPointerException on app restart

### ISSUE THREAD

**Issue by icode** [RuedigerMoeller/fast-serialization#71]
I use fst for memcached, but application restart throw error

```
Exception in thread "pool-3-thread-1" ameba.exception.AmebaException: java.io.IOException: java.lang.NullPointerException
	at ameba.cache.util.Serializations.asObject(Serializations.java:57)
	at ameba.cache.util.Serializations.asObject(Serializations.java:70)
	at ameba.cache.Cache.get(Cache.java:365)
	at com.sinitek.fiaame.resources.basedata.SecurityService.findStockSecurityList(SecurityService.java:27)
	at com.sinitek.fiaame.resources.common.CacheService.refreshStockList(CacheService.java:129)
	at com.sinitek.fiaame.resources.common.CacheService.doCache(CacheService.java:73)
	at com.sinitek.fiaame.resources.common.CacheFeature$1.run(CacheFeature.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	at ameba.cache.util.Serializations.asObject(Serializations.java:55)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:350)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:683)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:537)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:363)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
	at org.nustaq.serialization.serializers.FSTArrayListSerializer.instantiate(FSTArrayListSerializer.java:63)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:481)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:359)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:683)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:537)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:363)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:305)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:239)
	... 10 more
```

**Comment by icode** [comment]
change `FSTClazzNameRegistry` `FSTClazzInfo idToClz[]` to map, i want hash classs.getName() to integer. like -122222

**Comment by RuedigerMoeller** [comment]
seems like wrong class registration (must be exact same order at read and write time) or corrupted stream, or your classes changed meanwhile.


1) on a first attempt give up explicit class name registering, then check for the most often submitted classes and register them statically at reader and writer side (you can do this by string without referencing, see similar issues/questions)
2) You cannot uniquely "hash class names to an int" in a secure way, hashcode has collisions !. A Hashmap would slow down too much, there is a reason fst is fast :-).

**Comment by icode** [comment]
must be class register?

**Comment by icode** [comment]
I'm use for memcached mutil-app share data, horizontal expansion, how to use?

**Comment by RuedigerMoeller** [comment]
"must be class register?"

No you don't have to register classes. Its an optimization

"I'm use for memcached mutil-app share data, horizontal expansion, how to use?"

just similar to JDK Object Serialization

**Comment by icode** [comment]
but throw this `NullPointerException`

**Comment by icode** [comment]
```
public class Serializations {

    private static FSTConfiguration conf = null;

    private Serializations() {
    }

    public static void init() {
        if (conf == null)
            conf = FSTConf.createFastBinaryConfiguration();
    }

    public static void reinit() {
        conf = FSTConf.createFastBinaryConfiguration();
    }

    public static byte[] asBytes(final Object object) {
        ByteArrayOutputStream stream = new ByteArrayOutputStream(1024);
        FSTObjectOutput output = conf.getObjectOutput(stream);
        try {
            output.writeObject(object);
            output.flush();
            return stream.toByteArray();
        } catch (IOException e) {
            throw new AmebaException(e);
        } finally {
            IOUtils.closeQuietly(stream);
            output.resetForReUse();
        }
    }

    @SuppressWarnings("unchecked")
    public static <O> O asObject(final byte[] bytes) {
        FSTObjectInput in = conf.getObjectInput(bytes);
        try {
            return (O) in.readObject();
        } catch (ClassNotFoundException | IOException e) {
            throw new AmebaException(e);
        } finally {
            try {
                in.reset();
            } catch (IOException e) {
                // no op
            }
        }
    }

    @SuppressWarnings("unchecked")
    public static <O> O asObject(final Object bytes) {
        if (bytes instanceof byte[]) {
            return asObject((byte[]) bytes);
        }
        return (O) bytes;
    }

    public static void registerClass(Class... classes) {
        conf.registerClass(classes);
    }

    public static class FSTConf extends FSTConfiguration {

        private FSTConfiguration configuration;

        public FSTConf(FSTConfiguration configuration) {
            this.configuration = configuration;
        }

        public static FSTConfiguration getDefaultConfiguration() {
            return new FSTConf(FSTConfiguration.getDefaultConfiguration());
        }

        public static FSTConfiguration createMinBinConfiguration() {
            return new FSTConf(FSTConfiguration.createMinBinConfiguration());
        }

        public static FSTConfiguration createJsonConfiguration() {
            return new FSTConf(FSTConfiguration.createJsonConfiguration());
        }

        public static FSTConfiguration createJsonConfiguration(boolean prettyPrint, boolean shareReferences) {
            return new FSTConf(FSTConfiguration.createJsonConfiguration(prettyPrint, shareReferences));
        }

        public static FSTConfiguration createAndroidDefaultConfiguration() {
            return new FSTConf(FSTConfiguration.createAndroidDefaultConfiguration());
        }

        public static FSTConfiguration createDefaultConfiguration() {
            return new FSTConf(FSTConfiguration.createDefaultConfiguration());
        }

        public static FSTConfiguration initDefaultFstConfigurationInternal(FSTConfiguration conf) {
            return new FSTConf(FSTConfiguration.initDefaultFstConfigurationInternal(conf));
        }

        public static FSTConfiguration createFastBinaryConfiguration() {
            return new FSTConf(FSTConfiguration.createFastBinaryConfiguration());
        }

        public static FSTConfiguration createStructConfiguration() {
            return FSTConfiguration.createStructConfiguration();
        }

        @Override
        public ClassLoader getClassLoader() {
            return Thread.currentThread().getContextClassLoader();
        }

        @Override
        public void setClassLoader(ClassLoader classLoader) {
            configuration.setClassLoader(classLoader);
        }

        @Override
        public FSTClazzInfo getClassInfo(Class type) {
            return configuration.getClassInfo(type);
        }

        @Override
        public FSTObjectInput getObjectInput(InputStream in) {
            return configuration.getObjectInput(in);
        }

        @Override
        public FSTObjectInput getObjectInput() {
            return configuration.getObjectInput();
        }

        @Override
        public FSTObjectInput getObjectInput(byte[] arr) {
            return configuration.getObjectInput(arr);
        }

        @Override
        public FSTObjectInput getObjectInput(byte[] arr, int len) {
            return configuration.getObjectInput(arr, len);
        }

        @Override
        public FSTObjectOutput getObjectOutput(OutputStream out) {
            return configuration.getObjectOutput(out);
        }

        @Override
        public FSTObjectOutput getObjectOutput() {
            return configuration.getObjectOutput();
        }

        @Override
        public FSTObjectOutput getObjectOutput(byte[] outByte) {
            return configuration.getObjectOutput(outByte);
        }

        @Override
        public boolean isStructMode() {
            return configuration.isStructMode();
        }

        @Override
        public void setStructMode(boolean ignoreSerialInterfaces) {
            configuration.setStructMode(ignoreSerialInterfaces);
        }

        @Override
        public FSTClazzInfo getClazzInfo(Class rowClass) {
            return configuration.getClazzInfo(rowClass);
        }

        @Override
        public boolean isCrossPlatform() {
            return configuration.isCrossPlatform();
        }

        @Override
        public void setCrossPlatform(boolean crossPlatform) {
            configuration.setCrossPlatform(crossPlatform);
        }

        @Override
        public <T> T deepCopy(T metadata) {
            return configuration.deepCopy(metadata);
        }

        @Override
        public FSTEncoder createStreamEncoder() {
            return configuration.createStreamEncoder();
        }

        @Override
        public FSTDecoder createStreamDecoder() {
            return configuration.createStreamDecoder();
        }

        @Override
        public void registerCrossPlatformClassBinaryCache(String fulLQName, byte[] binary) {
            configuration.registerCrossPlatformClassBinaryCache(fulLQName, binary);
        }

        @Override
        public byte[] getCrossPlatformBinaryCache(String symbolicName) {
            return configuration.getCrossPlatformBinaryCache(symbolicName);
        }

        @Override
        public FSTConfiguration registerCrossPlatformClassMapping(String[][] keysAndVals) {
            return configuration.registerCrossPlatformClassMapping(keysAndVals);
        }

        @Override
        public FSTConfiguration registerCrossPlatformClassMapping(String shortName, String fqName) {
            return configuration.registerCrossPlatformClassMapping(shortName, fqName);
        }

        @Override
        public FSTConfiguration cpMap(String shortName, Class clz) {
            return configuration.cpMap(shortName, clz);
        }

        @Override
        public FSTConfiguration registerCrossPlatformClassMappingUseSimpleName(Class... classes) {
            return configuration.registerCrossPlatformClassMappingUseSimpleName(classes);
        }

        @Override
        public FSTConfiguration registerCrossPlatformClassMappingUseSimpleName(List<Class> classes) {
            return configuration.registerCrossPlatformClassMappingUseSimpleName(classes);
        }

        @Override
        public String getCPNameForClass(Class cl) {
            return configuration.getCPNameForClass(cl);
        }

        @Override
        public String getClassForCPName(String name) {
            return configuration.getClassForCPName(name);
        }

        @Override
        public Object asObject(byte[] b) {
            return configuration.asObject(b);
        }

        @Override
        public byte[] asByteArray(Object object) {
            return configuration.asByteArray(object);
        }

        @Override
        public byte[] asSharedByteArray(Object object, int[] length) {
            return configuration.asSharedByteArray(object, length);
        }

        @Override
        public String asJsonString(Object o) {
            return configuration.asJsonString(o);
        }

        @Override
        public void encodeToStream(OutputStream out, Object toSerialize) throws IOException {
            configuration.encodeToStream(out, toSerialize);
        }

        @Override
        public Object decodeFromStream(InputStream in) throws Exception {
            return configuration.decodeFromStream(in);
        }

        @Override
        public boolean isForceClzInit() {
            return configuration.isForceClzInit();
        }

        @Override
        public FSTConfiguration setForceClzInit(boolean forceClzInit) {
            return configuration.setForceClzInit(forceClzInit);
        }

        @Override
        public FSTClassInstantiator getInstantiator(Class clazz) {
            return configuration.getInstantiator(clazz);
        }

        @Override
        public void setInstantiator(FSTClassInstantiator instantiator) {
            configuration.setInstantiator(instantiator);
        }

        @Override
        public void registerSerializer(Class clazz, FSTObjectSerializer ser, boolean alsoForAllSubclasses) {
            configuration.registerSerializer(clazz, ser, alsoForAllSubclasses);
        }

        @Override
        public <T> T getCoderSpecific() {
            return configuration.getCoderSpecific();
        }

        @Override
        public void setCoderSpecific(Object coderSpecific) {
            configuration.setCoderSpecific(coderSpecific);
        }

        @Override
        public StreamCoderFactory getStreamCoderFactory() {
            return configuration.getStreamCoderFactory();
        }

        @Override
        public void setStreamCoderFactory(StreamCoderFactory streamCoderFactory) {
            configuration.setStreamCoderFactory(streamCoderFactory);
        }

        @Override
        public void returnObject(Object cached) {
            configuration.returnObject(cached);
        }

        @Override
        public boolean isPreferSpeed() {
            return configuration.isPreferSpeed();
        }

        @Override
        public void setPreferSpeed(boolean preferSpeed) {
            configuration.setPreferSpeed(preferSpeed);
        }

        @Override
        public int calcObjectSizeBytesNotAUtility(Object obj) throws IOException {
            return configuration.calcObjectSizeBytesNotAUtility(obj);
        }

        @Override
        public void setSerializerRegistryDelegate(FSTSerializerRegistryDelegate del) {
            configuration.setSerializerRegistryDelegate(del);
        }

        @Override
        public Object getCachedObject(Class cl) {
            return configuration.getCachedObject(cl);
        }

        @Override
        public boolean isForceSerializable() {
            return configuration.isForceSerializable();
        }

        @Override
        public FSTConfiguration setForceSerializable(boolean forceSerializable) {
            return configuration.setForceSerializable(forceSerializable);
        }

        @Override
        public void clearCaches() {
            configuration.clearCaches();
        }

        @Override
        public boolean isShareReferences() {
            return configuration.isShareReferences();
        }

        @Override
        public void setShareReferences(boolean shareReferences) {
            configuration.setShareReferences(shareReferences);
        }

        @Override
        public void registerClass(Class... c) {
            configuration.registerClass(c);
        }

        @Override
        public FSTClazzNameRegistry getClassRegistry() {
            return configuration.getClassRegistry();
        }

        @Override
        public FSTClazzInfoRegistry getCLInfoRegistry() {
            return configuration.getCLInfoRegistry();
        }
    }

}

```

**Comment by RuedigerMoeller** [comment]
Hm, to be honest its unclear what you are trying to achieve here. 
1) use getDefaultConfiguration() instead of getFastBinary(), difference is marginal (except for native arrays). Once your app is working, try fastbinary to check wether it makes a difference for your app
2) Don't subclass FSTConfiguration (why ?).
3) do not register classes. First get it to work, read the documentation, then register most frequent used classes if needed (pure performance optimization).

My version of this:
```java
public class Serializations {

    private static FSTConfiguration conf = FSTConf.createDefaultConfiguration();;

    private Serializations() {
    }
    public static void init() {
    }
    public static void reinit() {
    }
    public static byte[] asBytes(final Object object) {
        return conf.asByteArray(object);
    }

    @SuppressWarnings("unchecked")
    public static <O> O asObject(final byte[] bytes) {
        return (O)conf.asObject(bytes);
    }

    @SuppressWarnings("unchecked")
    public static <O> O asObject(final Object bytes) {
        if (bytes instanceof byte[]) {
            return asObject((byte[]) bytes);
        }
        return (O) bytes;
    }

    public static void registerClass(Class... classes) {
        // don't. FIRST get it to run THEN optimize
    }
```

**Comment by icode** [comment]
2) Because my class loader can be change at reload classes, and my class not loaded in LaunchLoader

**Comment by RuedigerMoeller** [comment]
on reload classes, create a new FSTConfiguration, and use FSTConfiguration.setClassLoader. Ensure you have the latest version (there where issues with classloaders in older versions). Also stick to defaultConfiguration as other configurations might not have been tested with classloading trickery.

**Comment by icode** [comment]
```
public class FSTSerializer implements Serializer {
    private static FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();

    public void registerClass(Class clazz) {
    }

    public byte[] asBytes(final Object object) {
        return conf.asByteArray(object);
    }

    @SuppressWarnings("unchecked")
    public <O> O asObject(final byte[] bytes) {
        return (O) conf.asObject(bytes);
    }

}
```

```

 +com.xxxx.fiaame.models.common.ZGJSettingÿý  ÿÿù ÿÿÿÿû [Z ÷ÿ÷ÿöÿüPARTMODEü  java.sql.Timestamp7ðøÔL  B   U7ðøÔL  B   
Exception in thread "pool-1-thread-1" java.lang.Error: java.io.IOException: java.lang.NullPointerException
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1151)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.lang.NullPointerException
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
    at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1033)
    at ameba.cache.util.FSTSerializer.asObject(FSTSerializer.java:28)
    at ameba.cache.util.Serializations.asObject(Serializations.java:32)
    at ameba.cache.util.Serializations.asObject(Serializations.java:38)
    at ameba.cache.Cache.get(Cache.java:365)
    at com.xxxx.fiaame.resources.common.SettingService.getSetting(SettingService.java:24)
    at com.xxxx.fiaame.resources.common.CacheService.refreshIndustry(CacheService.java:141)
    at com.xxxx.fiaame.resources.common.CacheService.doCache(CacheService.java:71)
    at com.xxxx.fiaame.resources.common.CacheFeature$1.run(CacheFeature.java:28)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    ... 2 more
Caused by: java.lang.NullPointerException
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:350)
    at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:683)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:537)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:363)
    at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:305)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:239)
    ... 12 more
```

**Comment by icode** [comment]
I have use ebean-orm, so BeanList and BeanMap is a wrap, is this issue?

like kyro i must be register
```
            SerializerFactory fieldSerializerFactory = new SerializerFactory() {
                @Override
                public com.esotericsoftware.kryo.Serializer makeSerializer(Kryo kryo, Class<?> type) {
                    return new FieldSerializer<>(kryo, BeanCollection.class.isAssignableFrom(type)
                            ? BeanCollection.class : SqlRow.class);
                }
            };

            addDefaultSerializer(BeanCollection.class, fieldSerializerFactory);
            addDefaultSerializer(SqlRow.class, fieldSerializerFactory);
```

**Comment by RuedigerMoeller** [comment]
FST mimics jdk serialization, so if the wrapper classes implement e.g. readReplace/writeReplace it should not be necessary to register serializers. Just do isolated tests. In case BeanList/BeanMap fail, you need to register dedicated FSTSerializers.

You can do a validation for debug once you are serializing like:
´´´java
public byte[] asBytes(final Object object) {
        byte res[] = conf.asByteArray(object);
        try {
           Object debug_dummy = conf.asObject(res);
        } catch (Exception e) {
           System.out.println("Failure to read/write :" + object );
        }
        return res;
}
```

You need to drill down the problem so I can help/debug.

**Comment by icode** [comment]
```
APPROVESTATUSü10 java.sql.Timestamp7Øé»L  B   U7Øé»L  B   
Failure to read/write :com.xxxx.fiaame.models.common.ZGJEnum@2
```

![2015-06-16 11 55 27](https://cloud.githubusercontent.com/assets/972959/8175576/fa9c75d4-141e-11e5-8fb0-7cee5d3edc0d.png)

**Comment by icode** [comment]
![5](https://cloud.githubusercontent.com/assets/972959/8175620/8fe2a064-141f-11e5-88e8-156174e36448.png)


tanks for help

**Comment by RuedigerMoeller** [comment]
I need the sourcecode of the problematic enum class ZGJEnum. Best would be an isolated testcase i can compile and debug here. 

kind regards,
ruediger

**Comment by icode** [comment]
This seems like my framework difference ClassLoader problem. I will continue to test.

Tanks for help, thanks

**Comment by RuedigerMoeller** [comment]
ok
