### ISSUE TITLE
Cannot deserialize URI or URL in unshared mode

### ISSUE THREAD

**Issue by vargusz** [RuedigerMoeller/fast-serialization#80]
With a configuration created by `FSTConfiguration.createDefaultConfiguration()` and `setShareReferences(false)`, `FSTObjectOutput.writeObject()` succeeds, but `FSTObjectInput.readObject()` fails with an `InvocationTargetException` wrapped inside an `IOException` for `URI` or `URL` instances.

If `setShareReferences(true)` is set, or `registerSerializer()` is used with a custom class that can write (`URI.toString()`) and read (`new URI(String)`) the object, then no exception occurs.

The stack trace:
```
Exception in thread "main" java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
	at com.example.test.Test.test(Test.java:40)
	at com.example.test.Test.main(Test.java:29)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:598)
	at org.nustaq.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:563)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:548)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	... 2 more
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:1060)
	at org.nustaq.serialization.FSTObjectInput$MyObjectStream.defaultReadObject(FSTObjectInput.java:1346)
	at java.net.URI.readObject(URI.java:1660)
	... 13 more
Caused by: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:353)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:701)
	at org.nustaq.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:1050)
	... 15 more
```

And the code used to reproduce the issue:
```java
package com.example.test;

import java.io.IOException;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import org.nustaq.serialization.FSTBasicObjectSerializer;
import org.nustaq.serialization.FSTClazzInfo;
import org.nustaq.serialization.FSTConfiguration;
import org.nustaq.serialization.FSTObjectInput;
import org.nustaq.serialization.FSTObjectOutput;

public class Test
{

    public static void main(final String[] args)
            throws Exception
    {
        URI uri = URI.create("http://example.com");
        URL url = uri.toURL();

        FSTConfiguration config = FSTConfiguration.createDefaultConfiguration();
        config.setShareReferences(false);
        //config.registerSerializer(URI.class, new FSTURISerializer(), true);
        //config.registerSerializer(URL.class, new FSTURLSerializer(), true);

        test(config, uri);
        test(config, url);
    }

    private static void test(FSTConfiguration config, Serializable object)
            throws IOException, ClassNotFoundException
    {
            FSTObjectOutput output = config.getObjectOutput();
            output.writeObject(object);
            byte[] serialized = output.getCopyOfWrittenBuffer();
            FSTObjectInput input = config.getObjectInput(serialized);
            Object result = input.readObject();
            System.out.println("equals: " + object.equals(result));
    }

    public static abstract class FSTStringBasedImmutableObjectSerializer<Type> extends FSTBasicObjectSerializer
    {

        @Override
        public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTClazzInfo.FSTFieldInfo referencedBy, int streamPosition)
                throws IOException
        {
            String s = toWrite.toString();
            out.writeStringUTF(s);
        }

        @Override
        public boolean alwaysCopy()
        {
            return true;
        }

        @Override
        public Object instantiate(Class objectClass, FSTObjectInput in, FSTClazzInfo serializationInfo, FSTClazzInfo.FSTFieldInfo referencee, int streamPosition)
                throws Exception
        {
            String s = in.readStringUTF();
            Object res = instantiate(s);
            return res;
        }

        protected abstract Type instantiate(String string)
                throws Exception;

    }

    public static class FSTURISerializer extends FSTStringBasedImmutableObjectSerializer<URI>
    {

        @Override
        protected URI instantiate(String string)
                throws URISyntaxException
        {
            return new URI(string);
        }

    }

    public static class FSTURLSerializer extends FSTStringBasedImmutableObjectSerializer<URL>
    {

        @Override
        protected URL instantiate(String string)
                throws MalformedURLException
        {
            return new URL(string);
        }

    }
}
```

Should serializing and deserializing instances of immutable JDK classes be supported in unshared mode, without registering custom serializers? If not, maybe the `FSTObjectOutput.writeObject()` call should already fail.

**Comment by RuedigerMoeller** [comment]
Thanks for the report + testcase, helps getting stuff done. I found the issue,
will be released with 2.37. If you want to access this immediately, just clone + mvn install.

Cheers, 
Ruediger =)

**Comment by RuedigerMoeller** [comment]
and don't forget to give a star ;)

**Comment by vargusz** [comment]
Thanks for the quick fix! Could you please let me know the expected release date of 2.37?

**Comment by RuedigerMoeller** [comment]
Within next 2 weeks, currently working on other changes to incorporate also with 2.37
