### ISSUE TITLE
Version tag not working with FST 2.14

### ISSUE THREAD

**Issue by rohitwalisnap** [RuedigerMoeller/fast-serialization#84]
I have a response object which is not being deserialized at client end and throwing the following error.

Setup Details:
Both Client and server are using FST 2.14.
My use case is that I have added a new field at server which is not present at client side. But I have added @version over that field at server side for backward compaitibilty. 
I have this field present inside a nested Object of the response object.

Its throwing the following error while deserializing at client end.
15:32:14,505# [requestId=144127452678801294] ERROR http-bio-10220-exec-26[FSTSerializationServiceImpl] - Exception occured during FST Deserialization
java.lang.RuntimeException: unable to encodeValue class from code 250
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:177)
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:405)
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:859)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:344)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:329)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:310)
        at com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl.doDeserialize(FSTSerializationServiceImpl.java:83)
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
        at com.myapp.code.logger.LogAspectHandler.logMethodExecutionTime(LogAspectHandler.java:60)
        at com.myapp.code.logger.LogAspectHandler.profileServiceCalls(LogAspectHandler.java:52)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy61.doDeserialize(Unknown Source)
        at com.myapp.base.spring.http.converter.SDServiceHttpMessageConverter.readInternal(SDServiceHttpMessageConverter.java:80)
        at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:180)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:95)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:162)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:123)
15:32:14,506# [requestId=144127452678801294] ERROR http-bio-10220-exec-26[SDServiceHttpMessageConverter] - error while de serializing request using deserializationService : com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl@55daab07
com.myapp.base.exception.SerializationException: Unable to deserialize through fst
        at com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl.doDeserialize(FSTSerializationServiceImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
        at com.myapp.code.logger.LogAspectHandler.logMethodExecutionTime(LogAspectHandler.java:60)
        at com.myapp.code.logger.LogAspectHandler.profileServiceCalls(LogAspectHandler.java:52)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy61.doDeserialize(Unknown Source)
        at com.myapp.base.spring.http.converter.SDServiceHttpMessageConverter.readInternal(SDServiceHttpMessageConverter.java:80)
        at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:180)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:95)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:162)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:123)
Caused by: java.lang.RuntimeException: unable to encodeValue class from code 250
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:177)
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:405)
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:859)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:344)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:329)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:310)
        at com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl.doDeserialize(FSTSerializationServiceImpl.java:83)
        ... 55 more15:32:14,505# [requestId=144127452678801294] ERROR http-bio-10220-exec-26[FSTSerializationServiceImpl] - Exception occured during FST Deserialization
java.lang.RuntimeException: unable to encodeValue class from code 250
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:177)
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:405)
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:859)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:344)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:329)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:310)
        at com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl.doDeserialize(FSTSerializationServiceImpl.java:83)
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
        at com.myapp.code.logger.LogAspectHandler.logMethodExecutionTime(LogAspectHandler.java:60)
        at com.myapp.code.logger.LogAspectHandler.profileServiceCalls(LogAspectHandler.java:52)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy61.doDeserialize(Unknown Source)
        at com.myapp.base.spring.http.converter.SDServiceHttpMessageConverter.readInternal(SDServiceHttpMessageConverter.java:80)
        at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:180)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:95)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:162)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:123)
15:32:14,506# [requestId=144127452678801294] ERROR http-bio-10220-exec-26[SDServiceHttpMessageConverter] - error while de serializing request using deserializationService : com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl@55daab07
com.myapp.base.exception.SerializationException: Unable to deserialize through fst
        at com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl.doDeserialize(FSTSerializationServiceImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
        at com.myapp.code.logger.LogAspectHandler.logMethodExecutionTime(LogAspectHandler.java:60)
        at com.myapp.code.logger.LogAspectHandler.profileServiceCalls(LogAspectHandler.java:52)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy61.doDeserialize(Unknown Source)
        at com.myapp.base.spring.http.converter.SDServiceHttpMessageConverter.readInternal(SDServiceHttpMessageConverter.java:80)
        at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:180)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:95)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:162)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:123)
Caused by: java.lang.RuntimeException: unable to encodeValue class from code 250
        at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:177)
        at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:405)
        at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:859)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:344)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:663)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:521)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:362)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:329)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:310)
        at com.myapp.base.transport.serialization.service.impl.FSTSerializationServiceImpl.doDeserialize(FSTSerializationServiceImpl.java:83)
        ... 55 more

My Response Object at Server side
public class MyAppResponse extends FSTServiceResponse {

    private static final long serialVersionUID = 4180807184662357818L;

    @Tag(10)
    private CodeSRO code;
}

public class CodeSRO implements Serializable {

    private static final long         serialVersionUID = -5384611645588792010L;

    @Tag(1)
    private Integer                   id;

    @Tag(2)
    @Pattern(regexp = "^[A-Za-z0-9_-]+$")
    @Size(min = 4)
    private String                    code;

    @Version(2)
    @Tag(35) @Pattern(regexp = "^[a-zA-Z0-9-_]+$") @Size(min=4)
    private String                    extCode;

Client side doesnt have extCode field.

**Comment by RuedigerMoeller** [comment]
Thanks for your report, I'll investigate as soon I find time.

**Comment by RuedigerMoeller** [comment]
It turns out you expect the OLD client to decode messages sent by the NEW server. However fst supports backward versioning only (NEW code can decode objects written by OLD version).
Supporting dual way backward compatibility would require excessive tagging of objects/fields inside the stream which in turn would degrade usability of fst for many hp use cases.
You need to figure out other ways, e.g. define new classes and detect client version upon connect or use the JSon codec which is more robust albeit much slower.

(see BasicFSTTest::testVersioningIssue84 verifying new-reads-old-object for your example)

**Comment by RuedigerMoeller** [comment]
clarified documentation on that
