### ISSUE TITLE
unable to decode

### ISSUE THREAD

**Issue by noamguy** [RuedigerMoeller/fast-serialization#88]
Hi,

Any idea why this may happen? I stream the data using socket and parse it on the client side..

My data is not long as u can see..

[DEBUG] 2015-09-29 16:00:11,574 io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
unable to decode:-&com.example.models.CacheMessageerrCodecommandputkeytravel	timestampTue Sep 29 16:00:11 UTC 2015valueï¿½{"body":"<html><a href=\"<CLICK_URL>\">AD VISUAL COMES HERE</a><html>","id":"ad123456","timestamp":"Tue Sep 29 16:00:11 UTC 2015","command":""}
[ERROR] 2015-09-29 16:00:11,706 com.example.utils.microservice.MicroServiceServer - IOException occured in process
java.io.IOException: java.lang.NegativeArraySizeException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1062)
	at com.example.utils.Serializer.deserialize(Serializer.java:20)
	at com.example.utils.microservice.MicroServiceServer.process(MicroServiceServer.java:42)
	at com.example.utils.microservice.MicroServiceServer.lambda$handle$1(MicroServiceServer.java:81)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:309)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$27(VertxNetHandler.java:54)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:312)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:217)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:54)
	at io.vertx.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NegativeArraySizeException
	at org.nustaq.serialization.minbin.MBIn.readArray(MBIn.java:99)
	at org.nustaq.serialization.minbin.MBTags$StringTagSer.readTag(MBTags.java:69)
	at org.nustaq.serialization.minbin.MBIn.readTag(MBIn.java:156)
	at org.nustaq.serialization.minbin.MBIn.readObject(MBIn.java:182)

Thanks :-)

**Comment by RuedigerMoeller** [comment]
You are reading with "MinBin" configuration, use
FSTConfiguration.createDefaultConfiguration() instead (sender and receiver
side). The MinBin format does only support a subset of JDK ser and is for
special purpose usage (cross language ..)

2015-09-29 18:05 GMT+02:00 noamguy <notifications@github.com>:

**Comment by noamguy** [comment]
Thanks :-)

I changed it and it now works!
