### ISSUE TITLE
show this exception:

### ISSUE THREAD

**Issue by wzlee** [RuedigerMoeller/fast-serialization#94]
message:"\u0001\u0000/org.hibernate.cache.internal.StandardQueryCache\u0003\u0005\u0000\u0001 org.hibernate.cache.spi.QueryKeyB�\u0001\u0001�\u0000\u0002[Z\u0001\u0001�����&\u0001\u0000\u0003\u0006�mK����\u007F\u0013�[X1%���\u00016select this_.id as id1_0_0_, this_.create_time as create_t2_0_0_, this_.creator as creator3_0_0_, this_.issue as issue4_0_0_, this_.modifier as modifier5_0_0_, this_.modify_time as modify_t6_0_0_, this_.summary as summary7_0_0_, this_.title as title8_0_0_ from test_cache_article this_ where this_.title like ?��\u0000\u001A[Lorg.hibernate.type.Type;\u0001\u0000\u0001\u001Dorg.hibernate.type.StringType\u0000\u00017org.hibernate.type.descriptor.java.StringTypeDescriptor�\u0000\u0010java.lang.String\u0000\u00018org.hibernate.internal.util.compare.ComparableComparator\u0000\u0001:org.hibernate.type.descriptor.java.ImmutableMutabilityPlan�\u0013\u0002�\u0000��\u00015org.hibernate.metamodel.relational.Size$LobMultiplier\u0000\u0000\u00017org.hibernate.type.descriptor.sql.VarcharTypeDescriptor�B\u0001\f\u0000\u0000\u0000"
10:44:30,801 ERROR [net.oschina.j2cache.Command]parse(line:97)Unabled to parse received command.
java.io.IOException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:168)
	at net.oschina.j2cache.util.FSTSerializer.deserialize(FSTSerializer.java:49)
	at net.oschina.j2cache.util.SerializationUtils.deserialize(SerializationUtils.java:66)
	at net.oschina.j2cache.Command.parse(Command.java:92)
	at net.oschina.j2cache.RedisCacheChannel.onMessage(RedisCacheChannel.java:287)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:129)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:102)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2591)
	at net.oschina.j2cache.RedisCacheChannel$1.run(RedisCacheChannel.java:60)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.ruedigermoeller.serialization.util.FSTUtil.rethrow(FSTUtil.java:119)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:467)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:435)
	at de.ruedigermoeller.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:396)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:262)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:230)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:210)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObject(FSTObjectInput.java:165)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:464)
	... 15 more
Caused by: java.lang.RuntimeException: unknown object tag -65
	at de.ruedigermoeller.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:291)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:255)
	at de.ruedigermoeller.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:537)
	at de.ruedigermoeller.serialization.FSTObjectInput$2.defaultReadObject(FSTObjectInput.java:1173)
	at de.ruedigermoeller.serialization.FSTObjectInput$MyObjectStream.defaultReadObject(FSTObjectInput.java:1474)
	at org.hibernate.cache.spi.QueryKey.readObject(QueryKey.java:205)
	... 20 more

**Comment by RuedigerMoeller** [comment]
The exception is not sufficient to make an analysis. Please provide:
* version of fst, jdk
* isolate which class/object structure fails and provide a reproducing test case

foremost ensure its not caused by trying to read outdated versions of your object (e.g. cache entries have been written with an older version of hibernate/your stuff)
